import type { Params, ClipboardEntry, ClipboardPreferences, ClipboardState } from './protocol';
import { transitionPlugins, createDisclosure } from './motion.js';
const make = <K extends keyof HTMLElementTagNameMap>(tag: K, text = '', cls = '') => { const n = document.createElement(tag); n.textContent = text; n.className = cls; return n; };
const languages = [['auto','自动（中文 → 英文，英文 → 中文）'],['zh-Hans','简体中文'],['zh-Hant','繁体中文'],['en','英文'],['en-US','美式英文'],['ja','日文'],['ko','韩文'],['ru','俄语'],['hi','印地语'],['de','德语']];
type Card = { node: HTMLElement; entry: ClipboardEntry; summary: HTMLButtonElement; title: HTMLElement; meta: HTMLElement; select: HTMLInputElement; body: HTMLElement; reveal: ReturnType<typeof createDisclosure>; opened: boolean; editor?: HTMLTextAreaElement; loaded?: ClipboardEntry; draft?: string; translation?: HTMLElement; request: number; };
export class ClipboardPage {
  readonly root = make('section', '', 'clipboard-page'); readonly entry = make('button', '复制粘贴', 'page-entry');
  private state?: ClipboardState; private opened = false; private disposed = false; private busy = false; private loading = false;
  private panel?: HTMLElement; private previousFocus?: HTMLElement; private scroll = 0; private seen = 0; private query = ''; private composing = false; private generation = 0;
  private list = make('div','','clipboard-grid'); private status = make('p','','hint'); private error = make('p','','transfer-error'); private empty = make('p'); private search = make('input');
  private cards = new Map<string,Card>(); private selected = new Set<string>(); private switches = new Map<keyof ClipboardPreferences,HTMLInputElement>();
  private maximum = make('input'); private excluded = make('input'); private target = make('select'); private back = make('button','返回设置'); private reset = make('button','备份并重置损坏历史');
  private menu?: HTMLElement; private menuReturn?: HTMLElement; private poll: ReturnType<typeof setInterval>; private searchTimer?: ReturnType<typeof setTimeout>;
  constructor(private call:(p:Params)=>Promise<ClipboardState>,private currentPanel:()=>HTMLElement,private beforeReturn:()=>Promise<void>,private confirm:(s:string)=>Promise<boolean>) {
    this.root.id='clipboard-page'; this.root.dataset.fullWindow='true'; this.entry.id='clipboard-open'; this.entry.onclick=()=>this.open();
    const head=make('div','','transfer-header'); this.back.id='clipboard-back';this.back.onclick=()=>void this.close();head.append(make('h2','复制粘贴'),this.back);this.root.append(head);
    this.root.append(make('p','复制的文字留在当前设备。显示提示、监听和保存历史分别控制；系统 Ctrl+V 与右键粘贴始终保持原有行为。','hint'));
    const prefs=make('div','','clipboard-preferences');this.root.append(prefs);
    for(const [key,label] of [['listening','监听文字剪贴板'],['show','显示复制粘贴提示'],['save','保存历史到本机'],['clearOnExit','退出时清空历史']] as const){const row=make('label','','transfer-enable'),input=make('input');input.type='checkbox';input.id='clipboard-'+key;input.setAttribute('role','switch');row.append(make('span',label),input);prefs.append(row);this.switches.set(key,input);input.onchange=()=>{const desired=input.checked;input.checked=this.state?.preferences[key]??false;void this.preferences({[key]:desired});};}
    const row=make('div','','clipboard-options');this.maximum.type='number';this.maximum.min='4';this.maximum.max='200';this.maximum.id='clipboard-maximum';const maxLabel=make('label','历史上限（4–200）');maxLabel.htmlFor=this.maximum.id;row.append(maxLabel,this.maximum);this.maximum.onchange=()=>void this.preferences({maximum:Number(this.maximum.value)});
    this.excluded.type='text';this.excluded.id='clipboard-excluded';const appLabel=make('label','暂停监听的应用（进程名，以分号分隔）');appLabel.htmlFor=this.excluded.id;const saveExcluded=make('button','保存排除应用');saveExcluded.onclick=()=>void this.preferences({excluded:this.excluded.value});row.append(appLabel,this.excluded,saveExcluded);prefs.append(row);
    this.target.id='clipboard-default-language';for(const [value,label] of languages){const o=make('option',label);o.value=value;this.target.append(o);}const targetLabel=make('label','默认翻译目标');targetLabel.htmlFor=this.target.id;prefs.append(targetLabel,this.target);this.target.onchange=()=>void this.preferences({target:this.target.value});
    this.root.append(make('p','默认保留最近 20 条；到达上限移除最旧记录。灵动岛只展示最近 4 条。关闭保存后历史仅在本次运行中保留；退出清空模式不把正文写入磁盘。排除应用不是可靠的密码识别器，可随时暂停监听。','hint'));
    const toolbar=make('div','','transfer-toolbar');this.search.type='search';this.search.placeholder='搜索完整文字';this.search.setAttribute('aria-label','搜索复制历史');this.search.id='clipboard-search';toolbar.append(this.search);
    this.search.addEventListener('compositionstart',()=>{this.composing=true;});this.search.addEventListener('compositionend',()=>{this.composing=false;this.searchChanged();});this.search.oninput=()=>{if(!this.composing)this.searchChanged();};
    const remove=make('button','删除所选'),clear=make('button','清空历史');remove.id='clipboard-delete-selected';clear.id='clipboard-clear';remove.onclick=()=>void this.run(async()=>{if(this.selected.size&&await this.confirm(`移除所选 ${this.selected.size} 条历史？系统剪贴板不变。`)){await this.call({action:'delete',ids:[...this.selected]});this.selected.clear();}});clear.onclick=()=>void this.run(async()=>{if(await this.confirm('清空全部复制历史？未保存的草稿也将移除，系统剪贴板不变。'))await this.call({action:'clear',confirmed:true});});toolbar.append(remove,clear);this.root.append(toolbar,this.error,this.status,this.reset,this.empty,this.list);this.status.setAttribute('role','status');this.error.setAttribute('role','alert');this.reset.hidden=true;
    this.reset.onclick=()=>void this.run(async()=>{if(await this.confirm('先保留损坏文件副本，再创建空历史并恢复默认设置？'))await this.call({action:'reset-corrupt',confirmed:true});});
    this.root.addEventListener('pointerdown',e=>{if(this.menu&&!this.menu.contains(e.target as Node))this.closeMenu();});window.addEventListener('keydown',this.key,true);
    this.poll=setInterval(()=>{if(!document.hidden)void this.refresh();},1000);void this.refresh();
  }
  private key=(e:KeyboardEvent)=>{if(e.key!=='Escape'||!this.opened||document.querySelector('dialog[open]')||document.querySelector('select:open'))return;e.preventDefault();e.stopImmediatePropagation();if(this.menu)this.closeMenu();else void this.close();};
  private searchChanged(){this.query=this.search.value;this.generation++;clearTimeout(this.searchTimer);this.searchTimer=setTimeout(()=>void this.refresh(),120);}
  private async preferences(patch:Partial<ClipboardPreferences>){if(!this.state)return;await this.run(async()=>{let confirmed=false;if(patch.maximum!==undefined&&patch.maximum<this.state!.preferences.maximum)confirmed=await this.confirm('降低上限会永久移除超出的最旧记录。继续？');if(patch.maximum!==undefined&&patch.maximum<this.state!.preferences.maximum&&!confirmed)return;await this.call({action:'preferences',preferences:{...this.state!.preferences,...patch},confirmed});});}
  private async run(fn:()=>Promise<void>){if(this.busy||this.disposed)return;this.busy=true;this.error.textContent='';this.root.setAttribute('aria-busy','true');try{await fn();}catch(e){this.error.textContent=String(e);}finally{this.busy=false;this.root.setAttribute('aria-busy','false');await this.refresh();}}
  async refresh(){if(this.loading||this.disposed)return;this.loading=true;const generation=this.generation;try{const state=await this.call({action:'list',query:this.query});if(this.disposed||generation!==this.generation)return;const changed=!this.state||this.state.revision!==state.revision||this.list.dataset.query!==this.query;this.state=state;
    for(const [key,input] of this.switches){input.checked=Boolean(state.preferences[key]);input.setAttribute('aria-checked',String(input.checked));}
    if(document.activeElement!==this.maximum)this.maximum.value=String(state.preferences.maximum);if(document.activeElement!==this.excluded)this.excluded.value=state.preferences.excluded;if(document.activeElement!==this.target)this.target.value=state.preferences.target;
    this.reset.hidden=!state.recoveryRequired;if(state.error)this.error.textContent=state.error;if(changed){this.render();this.list.dataset.query=this.query;}
    if(state.viewRequest>this.seen){this.seen=state.viewRequest;this.open();if(state.selected){const c=this.cards.get(state.selected);if(c)await this.expand(c,true);}}
  }catch(e){if(this.opened)this.error.textContent=String(e);}finally{this.loading=false;}}
  open(){if(this.opened)return;this.opened=true;if(!this.panel){this.previousFocus=document.activeElement as HTMLElement;this.panel=this.currentPanel();this.scroll=document.getElementById('content')!.scrollTop;}transitionPlugins(true,this.panel,this.root,this.entry,()=>this.back.focus({preventScroll:true}));void this.refresh();}
  async close(){if(!this.opened||!this.panel)return;this.closeMenu();this.opened=false;await this.beforeReturn().catch(e=>{this.error.textContent=String(e);});if(this.opened||this.disposed)return;const panel=this.panel;transitionPlugins(false,panel,this.root,this.entry,()=>{document.getElementById('content')!.scrollTop=this.scroll;(this.previousFocus?.isConnected?this.previousFocus:this.entry).focus({preventScroll:true});this.panel=undefined;});}
  private render(){if(!this.state)return;const ids=new Set(this.state.entries.map(e=>e.id));
    // Filtered-out cards retain editor drafts. A full query can distinguish deletion.
    for(const [id,c] of this.cards){c.node.hidden=!ids.has(id);if(!this.query&&!ids.has(id)){c.reveal.dispose();c.node.remove();this.cards.delete(id);this.selected.delete(id);}}
    let previous:HTMLElement|undefined;
    for(const entry of this.state.entries){let c=this.cards.get(entry.id);if(!c){const node=make('article','','clipboard-card'),summary=make('button','','clipboard-summary'),title=make('strong'),meta=make('span','','hint'),select=make('input'),clip=make('div','','clipboard-details'),body=make('div','','clipboard-detail-body');select.type='checkbox';select.setAttribute('aria-label','选择历史记录');const check=make('label','','clipboard-select');check.append(select,make('span','选择'));summary.append(title,meta);clip.id='clipboard-detail-'+entry.id;summary.setAttribute('aria-controls',clip.id);summary.setAttribute('aria-expanded','false');clip.append(body);node.append(summary,check,clip);node.dataset.id=entry.id;this.list.append(node);
      c={node,entry,summary,title,meta,select,body,reveal:createDisclosure(clip,body),opened:false,request:0};const card=c;this.cards.set(entry.id,c);summary.onclick=()=>void this.expand(card,!card.opened);select.onchange=()=>{select.checked?this.selected.add(entry.id):this.selected.delete(entry.id);};node.oncontextmenu=e=>{if((e.target as HTMLElement).closest('textarea,input,select'))return;e.preventDefault();this.context(card,e.clientX,e.clientY);};}
      c.node.hidden=false;c.entry=entry;c.title.textContent=entry.text||'（空文本）';c.summary.title='查看完整内容';c.meta.textContent=`${new Date(entry.created).toLocaleString()} · ${entry.characters} 字符${entry.modified?' · 已修改':''}${entry.translated?' · 已翻译':''}`;c.select.checked=this.selected.has(entry.id);
      // Only move nodes if ordering changes; polling never rebuilds focused editors.
      if(previous?previous.nextElementSibling!==c.node:this.list.firstElementChild!==c.node)this.list.insertBefore(c.node,previous?previous.nextSibling:this.list.firstChild);previous=c.node;
    }this.empty.textContent=ids.size?'':this.query?'没有匹配的复制内容':'暂无历史。复制一段文字后会在这里显示。';
  }
  private async expand(c:Card,open:boolean){c.opened=open;c.summary.setAttribute('aria-expanded',String(open));if(!open){c.reveal.set(false);return;}if(!c.editor){const serial=++c.request;try{const reply=await this.call({action:'get',id:c.entry.id});if(this.disposed||serial!==c.request)return;c.loaded=reply.entry!;this.editor(c);}catch(e){this.error.textContent=String(e);c.opened=false;c.summary.setAttribute('aria-expanded','false');return;}}c.reveal.set(c.opened);if(c.opened)c.editor?.focus({preventScroll:true});}
  private async translateText(params:Params){let r=await this.call({...params,action:'translate-start'});while(r.pending&&!this.disposed){await new Promise(resolve=>setTimeout(resolve,200));if(this.disposed)throw Error('页面已关闭');r=await this.call({action:'translation-read',requestId:params.requestId});}if(r.error)throw Error(r.error);return r;}
  private editor(c:Card){const entry=c.loaded!;const text=make('textarea');text.value=c.draft??entry.text;text.maxLength=262144;text.setAttribute('aria-label','编辑完整复制内容');text.spellcheck=false;c.editor=text;const ops=make('div','','actions'),info=make('p',`来源：${entry.source||'无法获取'}。修改仅在“保存修改”后写入历史。`,'hint'),translated=make('pre','','clipboard-translation');c.translation=translated;translated.hidden=!entry.translation;translated.textContent=entry.translation||'';
    text.oninput=()=>{c.draft=text.value;};text.onkeydown=e=>{if(e.ctrlKey&&e.key.toLowerCase()==='s'){e.preventDefault();void save();}};
    // Native selection/menu and IME remain intact; only copy is routed to suppress recapture.
    text.addEventListener('copy',e=>{e.preventDefault();const selected=text.value.slice(text.selectionStart,text.selectionEnd);if(selected)void this.run(async()=>{await this.call({action:'copy-text',text:selected});this.status.textContent='已复制选中文字';});});
    const button=(label:string,run:()=>Promise<void>)=>{const b=make('button',label);b.onclick=()=>void this.run(run);ops.append(b);return b;};
    const save=async()=>{await this.call({action:'save',id:c.entry.id,text:text.value,version:c.loaded!.version});const latest=await this.call({action:'get',id:c.entry.id});c.loaded=latest.entry;c.draft=undefined;this.status.textContent='修改已保存';translated.hidden=true;};
    button('保存修改',save);button('取消修改',async()=>{text.value=c.loaded!.text;c.draft=undefined;});button('复制草稿（不保存）',async()=>{await this.call({action:'copy-text',text:text.value});this.status.textContent='已复制草稿，可在目标应用按 Ctrl+V；历史未被覆盖';});
    button('删除记录',async()=>{if(await this.confirm('删除本条历史及未保存的草稿？系统剪贴板不变。'))await this.call({action:'delete',id:c.entry.id});});
    const language=make('select');language.setAttribute('aria-label','翻译目标语言');for(const [code,label] of languages){const o=make('option',label);o.value=code;language.append(o);}language.value=this.state?.preferences.target??'auto';
    const translate=make('button','快捷翻译');let request=0;translate.onclick=()=>{const current=++request;const value=text.selectionEnd>text.selectionStart?text.value.slice(text.selectionStart,text.selectionEnd):text.value;const draft=text.value;translate.disabled=true;void this.translateText({id:c.entry.id,text:value,target:language.value,requestId:crypto.randomUUID(),source:'auto'}).then(result=>{if(this.disposed||current!==request||text.value!==draft)return;translated.hidden=false;translated.textContent='译文（保留原文）\n'+result.translation;this.status.textContent='翻译完成';},e=>{if(current===request)this.error.textContent=String(e);}).finally(()=>{if(current===request)translate.disabled=false;});};
    const cancel=make('button','取消翻译');cancel.onclick=()=>{++request;translate.disabled=false;void this.call({action:'cancel-translation'}).catch(e=>{this.error.textContent=String(e);});};ops.append(translate,language,cancel);
    const exportPart=make('select');exportPart.setAttribute('aria-label','导出内容');for(const [value,label] of [['original','当前已保存原文'],['translation','译文'],['both','原文和译文']]){const o=make('option',label);o.value=value;exportPart.append(o);}ops.append(exportPart);button('直接导出…',async()=>{const result=await this.call({action:'export',id:c.entry.id,part:exportPart.value});this.status.textContent=result.cancelled?'已取消导出':result.exported?'已导出完整文本':'';});
    c.body.append(ops,info,text,translated,make('p','翻译仅在明确点击后调用服务。未配置服务时不会发送文字。选区操作可使用编辑器右键菜单；快捷翻译优先处理选中的文字。','hint'));
  }
  private closeMenu(){this.menu?.remove();this.menu=undefined;this.menuReturn?.focus({preventScroll:true});}
  private context(c:Card,x:number,y:number){this.closeMenu();this.menuReturn=c.summary;const menu=make('div','','transfer-context');menu.setAttribute('role','menu');this.menu=menu;const add=(label:string,run:()=>Promise<void>)=>{const b=make('button',label);b.setAttribute('role','menuitem');b.onclick=()=>{this.closeMenu();void this.run(run);};menu.append(b);};add('复制',async()=>{await this.call({action:'copy',id:c.entry.id});this.status.textContent='已复制完整文本';});add('预览与修改',()=>this.expand(c,true));add('删除',async()=>{if(await this.confirm('删除这条历史？'))await this.call({action:'delete',id:c.entry.id});});add('翻译',async()=>{await this.expand(c,true);Array.from(c.body.querySelectorAll('button')).find(b=>b.textContent==='快捷翻译')?.click();});add('直接导出…',async()=>{const r=await this.call({action:'export',id:c.entry.id,part:'original'});this.status.textContent=r.cancelled?'已取消导出':'已导出完整文本';});
    this.root.append(menu);const bounds=menu.getBoundingClientRect();menu.style.left=Math.max(8,Math.min(x,innerWidth-bounds.width-8))+'px';menu.style.top=Math.max(8,Math.min(y,innerHeight-bounds.height-8))+'px';menu.querySelector('button')?.focus();menu.onkeydown=e=>{const buttons=Array.from(menu.querySelectorAll('button')),i=buttons.indexOf(document.activeElement as HTMLButtonElement);if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();buttons[(i+(e.key==='ArrowDown'?1:buttons.length-1))%buttons.length].focus();}};
  }
  dispose(){this.disposed=true;clearInterval(this.poll);clearTimeout(this.searchTimer);this.closeMenu();window.removeEventListener('keydown',this.key,true);this.cards.forEach(c=>c.reveal.dispose());void this.call({action:'cancel-translation'}).catch(()=>{});}
}
