// Multi-platform protocol adapters. Adapted from WXRIW/Lyricify-Lyrics-Helper
// (Apache-2.0), pinned revision documented in source/third_party/lyricify.
#include "lyrics_providers.h"
#include "lyrics_crypto.h"
#include <winrt/Windows.Data.Json.h>
#include <winrt/Windows.Foundation.Collections.h>
namespace wi {
using namespace winrt::Windows::Data::Json;
bool lyricsMetadataMatch(const LyricsMetadata&,const Music&,bool);
namespace {
JsonObject obj(JsonObject const& o,const wchar_t* k){return o.GetNamedObject(k,JsonObject());}
JsonArray arr(JsonObject const& o,const wchar_t* k){return o.GetNamedArray(k,JsonArray());}
std::wstring txt(JsonObject const& o,const wchar_t* k){auto v=o.GetNamedValue(k,JsonValue::CreateNullValue());return v.ValueType()==JsonValueType::String?std::wstring(v.GetString().c_str()):v.ValueType()==JsonValueType::Number?std::to_wstring((int64_t)v.GetNumber()):L"";}
std::string json(JsonObject const& o){return utf8(o.Stringify().c_str());}
void put(JsonObject& o,const wchar_t* k,const std::wstring& v){o.Insert(k,JsonValue::CreateStringValue(v));}
void put(JsonObject& o,const wchar_t* k,double v){o.Insert(k,JsonValue::CreateNumberValue(v));}
std::wstring enc(const std::wstring& w){auto s=utf8(w);std::wstring out;const wchar_t* h=L"0123456789ABCDEF";for(unsigned char c:s){if(isalnum(c)||c=='_'||c=='-'||c=='.'||c=='~')out+=(wchar_t)c;else {out+=L'%';out+=h[c>>4];out+=h[c&15];}}return out;}
std::wstring artists(JsonArray const& a){std::wstring out;for(auto x:a){auto s=txt(x.GetObject(),L"name");if(!s.empty()){if(!out.empty())out+=L" / ";out+=s;}}return out;}
LyricsCandidate candidate(JsonObject const& o,const wchar_t* artist,const wchar_t* album,const wchar_t* duration){return {{txt(o,L"name"),artists(arr(o,artist)),txt(obj(o,album),L"name"),o.GetNamedNumber(duration,0)/1000},txt(o,L"id"),{}};}
std::wstring appleHeaders(const LyricsCredentials& c){return L"Origin: https://music.apple.com\r\nAuthorization: Bearer "+c.accessToken+L"\r\nmedia-user-token: "+c.mediaToken+L"\r\nAccept-Language: "+c.language+L"\r\n";}
JsonObject metadataJson(const LyricsMetadata& m){JsonObject o;put(o,L"title",m.title);put(o,L"artist",m.artist);put(o,L"album",m.album);put(o,L"duration",m.duration);return o;}
std::string cacheName(const Music& m,const std::wstring& provider){return sha256(utf8(m.title+L"\n"+m.artist+L"\n"+m.album+L"\n"+std::to_wstring(m.duration)+L"\n"+provider));}
double epoch(){return (double)std::chrono::duration_cast<std::chrono::seconds>(std::chrono::system_clock::now().time_since_epoch()).count();}
JsonArray saveLines(const std::vector<LyricsLine>& lines){JsonArray out;for(auto& l:lines){JsonObject o;put(o,L"start",l.start);put(o,L"end",l.end);put(o,L"text",l.text);put(o,L"translation",l.translation);put(o,L"romanization",l.romanization);put(o,L"agent",l.agent);JsonArray words;for(auto& w:l.syllables){JsonObject x;put(x,L"start",w.start);put(x,L"end",w.end);put(x,L"text",w.text);words.Append(x);}o.Insert(L"syllables",words);o.Insert(L"background",saveLines(l.background));out.Append(o);}return out;}
std::vector<LyricsLine> loadLines(JsonArray a,int depth=0){if(depth>8||a.Size()>10000)throw std::runtime_error("cache bounds");std::vector<LyricsLine> out;for(auto v:a){auto o=v.GetObject();LyricsLine l;l.start=o.GetNamedNumber(L"start");l.end=o.GetNamedNumber(L"end");if(!std::isfinite(l.start)||!std::isfinite(l.end)||l.start<0||l.end<l.start||l.end>86400)throw std::runtime_error("cache time");l.text=txt(o,L"text");l.translation=txt(o,L"translation");l.romanization=txt(o,L"romanization");l.agent=txt(o,L"agent");auto words=arr(o,L"syllables");if(words.Size()>10000)throw std::runtime_error("cache words");for(auto x:words){auto w=x.GetObject();auto b=w.GetNamedNumber(L"start"),e=w.GetNamedNumber(L"end");if(!std::isfinite(b)||!std::isfinite(e)||b<0||e<b||e>86400)throw std::runtime_error("cache word time");l.syllables.push_back({b,e,txt(w,L"text")});}l.background=loadLines(arr(o,L"background"),depth+1);out.push_back(std::move(l));}return out;}
std::string saveDocument(const LyricsDocument& d,const std::string& key){JsonObject o;put(o,L"schema",1);put(o,L"stored",epoch());put(o,L"key",wide(key));put(o,L"provider",d.provider);put(o,L"format",d.format);put(o,L"offset",d.offsetMs);put(o,L"plain",d.plain);put(o,L"language",d.language);put(o,L"original",wide(lyricsBase64(d.original)));put(o,L"degraded",d.degradedToLines?1:0);o.Insert(L"metadata",metadataJson(d.metadata));o.Insert(L"lines",saveLines(d.lines));return json(o);}
std::optional<LyricsDocument> loadDocument(const std::string& raw,const std::string& key,const std::wstring& provider){try{auto o=JsonObject::Parse(wide(raw));double age=epoch()-o.GetNamedNumber(L"stored");if(o.GetNamedNumber(L"schema")!=1||txt(o,L"key")!=wide(key)||txt(o,L"provider")!=provider||age<0||age>30*86400)return {};LyricsDocument d;d.provider=provider;d.format=txt(o,L"format");d.offsetMs=(int)o.GetNamedNumber(L"offset");d.language=txt(o,L"language");d.plain=txt(o,L"plain");d.original=lyricsBase64(utf8(txt(o,L"original")),true);d.degradedToLines=o.GetNamedNumber(L"degraded",0)!=0;d.lines=loadLines(arr(o,L"lines"));auto m=obj(o,L"metadata");d.metadata={txt(m,L"title"),txt(m,L"artist"),txt(m,L"album"),m.GetNamedNumber(L"duration",0)};for(auto& l:d.lines){d.characterSynchronized|=!l.syllables.empty();d.hasTranslation|=!l.translation.empty();d.hasRomanization|=!l.romanization.empty();}if(d.lines.empty()&&d.plain.empty())return {};return d;}catch(...){return {};}}
}
const std::vector<LyricsProviderInfo>& LyricsProviderRegistry::providers(){static std::vector<LyricsProviderInfo> list={{L"netease",L"网易云音乐",L"LRC,YRC",true,true,true,10},{L"qq_music",L"QQ 音乐",L"QRC,LRC",true,true,true,20},{L"kugou",L"酷狗音乐",L"KRC,LRC",true,true,true,30},{L"soda_music",L"汽水音乐",L"LRC",false,true,false,40},{L"apple_music",L"Apple Music",L"TTML",true,true,true,50},{L"lrclib",L"LRCLIB",L"LRC,TEXT",false,false,false,60}};return list;}
std::vector<std::wstring> LyricsProviderRegistry::order(const Music& song,int mode){if(mode==3||mode==5)return {L"netease"};if(mode==6)return {L"qq_music"};if(mode==7)return {L"kugou"};if(mode==8)return {L"soda_music"};if(mode==9)return {L"apple_music"};if(mode==1||mode==4)return {L"lrclib"};if(mode==2)return {};std::vector<std::wstring> out={L"netease",L"qq_music",L"kugou",L"soda_music",L"apple_music",L"lrclib"};auto platform=normalizeSong(song.platform);std::wstring preferred=platform.find(L"qq")!=platform.npos?L"qq_music":platform.find(L"汽水")!=platform.npos?L"soda_music":platform.find(L"酷狗")!=platform.npos?L"kugou":platform.find(L"apple")!=platform.npos?L"apple_music":L"netease";auto it=std::find(out.begin(),out.end(),preferred);std::rotate(out.begin(),it,it+1);return out;}
LyricsHttpResponse LyricsProviderRegistry::get(const LyricsHttpRequest& query,const LyricsRequest& request){LyricsHttpResponse r;auto end=query.url.find(L'/',8);auto host=query.url.substr(0,end);if(backoff[host]>now()){r.error=LyricsError::limited;return r;}
    for(int attempt=0;attempt<2;++attempt){if(!request.valid()){r.error=LyricsError::cancelled;return r;}r=transport(query,request.valid);r.retries=attempt;bool retry=r.error==LyricsError::network||r.error==LyricsError::timeout||r.status==429||r.status>=500;if(!retry||attempt==1)break;for(int i=0;i<25&&request.valid();++i)std::this_thread::sleep_for(std::chrono::milliseconds(10));}
    if(r.status==429||r.status>=500)backoff[host]=now()+30;return r;}
std::vector<LyricsCandidate> LyricsProviderRegistry::search(const std::wstring& id,const LyricsRequest& req,LyricsError& error){
    LyricsHttpRequest q;auto term=req.song.title+L" "+req.song.artist;const auto form=L"Content-Type: application/x-www-form-urlencoded\r\nReferer: https://music.163.com/\r\n";
    if(id==L"netease"){JsonObject o;put(o,L"s",term);put(o,L"type",L"1");put(o,L"limit",L"30");put(o,L"offset",L"0");put(o,L"total",L"true");q={L"https://interface.music.163.com/eapi/cloudsearch/pc",L"POST",form,neteaseEapi("/api/cloudsearch/pc",json(o))};}
    else if(id==L"qq_music"){JsonObject param;put(param,L"num_per_page",20);put(param,L"page_num",1);put(param,L"query",term);put(param,L"search_type",0);JsonObject call;put(call,L"module",L"music.search.SearchCgiService");put(call,L"method",L"DoSearchForQQMusicDesktop");call.Insert(L"param",param);JsonObject o;o.Insert(L"req_1",call);q={L"https://u.y.qq.com/cgi-bin/musicu.fcg",L"POST",L"Content-Type: application/json\r\nReferer: https://c.y.qq.com/\r\n",json(o)};}
    else if(id==L"kugou")q.url=L"https://lyrics.kugou.com/search?ver=1&man=yes&client=pc&keyword="+enc(term)+(req.song.duration>0?L"&duration="+std::to_wstring((int64_t)(req.song.duration*1000)):L"");
    else if(id==L"soda_music")q={L"https://api.qishui.com/luna/search/track?device_platform=android&os=android&ssmix=a&aid=386088&app_name=luna&version_code=100198030&version_name=19.8.0&manifest_version_code=100198030&update_version_code=100198030&channel=xiaomi_8478_64&resolution=1080*1920&dpi=480&device_type=ABR-AL80&device_brand=HUAWEI&language=zh&os_api=35&os_version=15&ac=wifi&device_model=ABR-AL80&tz_name=Asia%2FShanghai&tz_offset=28800&package=com.luna.music&sim_region=cn&q="+enc(term)+L"&cursor=0&count=20",L"GET",L"User-Agent: com.luna.music/100198030 (Linux; U; Android 15; zh_CN_#Hans; ABR-AL80; Build/V417IR;tt-ok/3.12.13.19)\r\n"};
    else if(id==L"apple_music"){if(req.credentials.mediaToken.empty()||req.credentials.accessToken.empty()){error=LyricsError::tokenMissing;return {};}q={L"https://amp-api.music.apple.com/v1/catalog/"+enc(req.credentials.storefront)+L"/search?types=songs&limit=20&term="+enc(term)+L"&l="+enc(req.credentials.language),L"GET",appleHeaders(req.credentials)};}
    else if(id==L"lrclib")q.url=L"https://lrclib.net/api/search?track_name="+enc(req.song.title)+L"&artist_name="+enc(req.song.artist);
    else {error=LyricsError::unavailable;return {};}
    auto r=get(q,req);error=r.error;if(error!=LyricsError::none)return {};std::vector<LyricsCandidate> list;
    if(id==L"lrclib"){for(auto x:JsonArray::Parse(wide(r.body))){auto o=x.GetObject();list.push_back({{txt(o,L"trackName"),txt(o,L"artistName"),txt(o,L"albumName"),o.GetNamedNumber(L"duration",0)},txt(o,L"id"),wide(json(o))});}return list;}
    auto o=JsonObject::Parse(wide(r.body));auto code=o.GetNamedNumber(L"code",0);if(code==429){error=LyricsError::limited;return {};}if(code!=0&&code!=200){error=LyricsError::unavailable;return {};}
    if(id==L"netease")for(auto v:arr(obj(o,L"result"),L"songs")){auto s=v.GetObject();list.push_back(candidate(s,s.HasKey(L"ar")?L"ar":L"artists",s.HasKey(L"al")?L"al":L"album",s.HasKey(L"dt")?L"dt":L"duration"));}
    else if(id==L"qq_music")for(auto v:arr(obj(obj(obj(obj(o,L"req_1"),L"data"),L"body"),L"song"),L"list")){auto s=v.GetObject();list.push_back({{txt(s,L"name"),artists(arr(s,L"singer")),txt(obj(s,L"album"),L"name"),s.GetNamedNumber(L"interval",0)},txt(s,L"id"),txt(s,L"mid")});}
    else if(id==L"kugou")for(auto v:arr(o,L"candidates")){auto s=v.GetObject();list.push_back({{txt(s,L"song"),txt(s,L"singer"),L"",s.GetNamedNumber(L"duration",0)/1000},txt(s,L"id"),txt(s,L"accesskey")});}
    else if(id==L"soda_music")for(auto group:arr(o,L"result_groups"))for(auto v:arr(group.GetObject(),L"data")){auto s=obj(obj(v.GetObject(),L"entity"),L"track");list.push_back(candidate(s,L"artists",L"album",L"duration"));}
    else if(id==L"apple_music")for(auto v:arr(obj(obj(o,L"results"),L"songs"),L"data")){auto s=v.GetObject(),a=obj(s,L"attributes");list.push_back({{txt(a,L"name"),txt(a,L"artistName"),txt(a,L"albumName"),a.GetNamedNumber(L"durationInMillis",0)/1000},txt(s,L"id"),L""});}
    return list;
}
LyricsResponse LyricsProviderRegistry::fetch(const std::wstring& id,const LyricsCandidate& song,const LyricsRequest& req){
    LyricsResponse out;LyricsHttpRequest q;
    if(id==L"netease"){JsonObject o;put(o,L"id",song.id);put(o,L"cp",L"false");for(auto key:{L"lv",L"kv",L"tv",L"rv",L"yv",L"ytv",L"yrv"})put(o,key,L"0");q={L"https://interface3.music.163.com/eapi/song/lyric/v1",L"POST",L"Content-Type: application/x-www-form-urlencoded\r\nReferer: https://music.163.com/\r\n",neteaseEapi("/api/song/lyric/v1",json(o))};}
    else if(id==L"qq_music")q={L"https://c.y.qq.com/qqmusic/fcgi-bin/lyric_download.fcg",L"POST",L"Content-Type: application/x-www-form-urlencoded\r\nReferer: https://c.y.qq.com/\r\n","version=15&miniversion=82&lrctype=4&musicid="+utf8(enc(song.id))};
    else if(id==L"kugou")q.url=L"https://lyrics.kugou.com/download?ver=1&client=pc&id="+enc(song.id)+L"&accesskey="+enc(song.auxiliary)+L"&fmt=krc&charset=utf8";
    else if(id==L"soda_music")q={L"https://beta-luna.douyin.com/luna/h5/seo_track?track_id="+enc(song.id)+L"&device_platform=web",L"GET",L"User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/124.0.0.0 Safari/537.36\r\n"};
    else if(id==L"apple_music")q={L"https://amp-api.music.apple.com/v1/catalog/"+enc(req.credentials.storefront)+L"/songs/"+enc(song.id)+L"?include%5Bsongs%5D=syllable-lyrics,lyrics&extend=ttmlLocalizations&l="+enc(req.credentials.language),L"GET",appleHeaders(req.credentials)};
    else if(id==L"lrclib"){auto o=JsonObject::Parse(song.auxiliary);out.document=parseNativeLyrics(utf8(txt(o,L"syncedLyrics")),"lrc");if(!out.document)out.document=parseNativeLyrics(utf8(txt(o,L"plainLyrics")),"text");if(!out.document)out.error=LyricsError::empty;return out;}
    auto r=get(q,req);out.error=r.error;if(r.error!=LyricsError::none)return out;
    if(id==L"netease"){out.document=parseProviderLyrics(r.body,id);if(!out.document&&req.valid()){JsonObject o;put(o,L"id",song.id);put(o,L"lv",L"-1");put(o,L"kv",L"-1");put(o,L"tv",L"-1");put(o,L"rv",L"-1");put(o,L"csrf_token",L"");auto fallback=get({L"https://music.163.com/weapi/song/lyric?csrf_token=",L"POST",q.headers,neteaseWeapi(json(o))},req);if(fallback.error==LyricsError::none)out.document=parseProviderLyrics(fallback.body,id);else out.error=fallback.error;}}
    else if(id==L"qq_music"){
        for(auto marker:{"<!--","-->"}){size_t p;while((p=r.body.find(marker))!=r.body.npos)r.body.erase(p,strlen(marker));}
        auto xml=readLyricsXml(r.body);std::optional<LyricsDocument> translated,romanized;
        if(xml){std::function<void(const LyricsXml&)> visit=[&](auto& n){if(n.name==L"content"||n.name==L"contentts"||n.name==L"contentroma"){auto raw=utf8(n.text());raw.erase(std::remove_if(raw.begin(),raw.end(),[](unsigned char c){return isspace(c);}),raw.end());auto p=decryptQrc(raw);std::optional<LyricsDocument> doc;if(p){doc=parseNativeLyrics(*p,"qrc-text");if(!doc)doc=parseNativeLyrics(*p,"lrc");}else if(n.text().find(L'[')!=std::wstring::npos)doc=parseNativeLyrics(utf8(n.text()),"lrc");if(n.name==L"content")out.document=std::move(doc);else if(n.name==L"contentts")translated=std::move(doc);else romanized=std::move(doc);}for(auto& c:n.children)visit(c);};visit(*xml);}
        if(out.document){if(translated)mergeLyricsTrack(*out.document,*translated,false);if(romanized)mergeLyricsTrack(*out.document,*romanized,true);}else out.error=LyricsError::decrypt;
    }else if(id==L"kugou"){auto o=JsonObject::Parse(wide(r.body));auto plain=decryptKrc(utf8(txt(o,L"content")));if(plain)out.document=parseNativeLyrics(*plain,"krc-text");else out.error=LyricsError::decrypt;}
    else if(id==L"soda_music"){auto o=obj(JsonObject::Parse(wide(r.body)),L"lyric");out.document=parseNativeLyrics(utf8(txt(o,L"content")),"lrc");if(out.document){auto t=parseNativeLyrics(utf8(txt(obj(o,L"translations"),L"cn")),"lrc");if(!t){auto langs=obj(o,L"lang_translations");for(auto language:{L"zh-Hans",L"zh",L"cn"}){t=parseNativeLyrics(utf8(txt(obj(langs,language),L"content")),"lrc");if(t)break;}}if(t)mergeLyricsTrack(*out.document,*t,false);}}
    else if(id==L"apple_music")out.document=parseProviderLyrics(r.body,id);
    if(!out.document&&out.error==LyricsError::none)out.error=r.body.empty()?LyricsError::empty:LyricsError::parse;return out;
}
LyricsResponse LyricsProviderRegistry::request(const LyricsRequest& req,int mode){
    auto ids=order(req.song,mode);LyricsResponse last;last.error=LyricsError::notFound;
    for(auto& id:ids){if(!req.valid()){last.error=LyricsError::cancelled;return last;}auto key=cacheName(req.song,id);auto cached=loadDocument(readFile(store/(key+".json"),16*1024*1024),key,id);if(cached){monitor.event("lyrics provider="+utf8(id)+" request_id="+std::to_string(req.requestId)+" status=ok cache_hit=1");return {std::move(cached),LyricsError::none,true};}}
    std::optional<LyricsDocument> plain;
    for(auto& id:ids){if(!req.valid())return {{},LyricsError::cancelled};auto started=now();LyricsError error=LyricsError::none;
        try{auto candidates=search(id,req,error);std::vector<LyricsCandidate> matched;for(auto& c:candidates)if(!c.id.empty()&&lyricsMetadataMatch(c.metadata,req.song,true))matched.push_back(c);
            // Different recording IDs are ambiguous without album/duration evidence.
            std::stable_sort(matched.begin(),matched.end(),[&](auto& a,auto& b){auto score=[&](auto& c){return std::make_pair(normalizeSong(c.metadata.album)==normalizeSong(req.song.album)?0:1,std::abs(c.metadata.duration-req.song.duration));};return score(a)<score(b);});
            if(matched.size()>1&&req.song.duration<=0&&req.song.album.empty())matched.clear();
            if(error==LyricsError::none&&!matched.empty()){last=fetch(id,matched.front(),req);if(last.document){auto& d=*last.document;d.provider=id;d.metadata=matched.front().metadata;d.degradedToLines=!d.characterSynchronized;error=LyricsError::none;if(req.valid())try{auto key=cacheName(req.song,id);writeAtomic(store/(key+".json"),saveDocument(d,key));}catch(...){}if(d.lines.empty()){if(!plain)plain=std::move(d);last.document.reset();} }
                else error=last.error;
            }else {if(error==LyricsError::none)error=LyricsError::notFound;last.error=error;}
        }catch(...){error=LyricsError::parse;last.error=error;}
        // Metadata is logged as hashes: diagnostics retain correlation without song/title text or credentials.
        monitor.event("lyrics provider="+utf8(id)+" request_id="+std::to_string(req.requestId)+" song_title_hash="+sha256(utf8(req.song.title)).substr(0,12)+" artist_hash="+sha256(utf8(req.song.artist)).substr(0,12)+" format="+(last.document?utf8(last.document->format):"none")+" status="+(last.document?"ok":"failed")+" error_code="+std::to_string((int)error)+" elapsed_ms="+std::to_string((int)((now()-started)*1000))+" cache_hit=0");
        if(last.document&&req.valid())return last;
    }if(!req.valid())return {{},LyricsError::cancelled};if(plain)return {std::move(plain),LyricsError::none};return last;
}
void LyricsProviderRegistry::clear(const Music& song){std::error_code ec;for(auto& p:providers())fs::remove(store/(cacheName(song,p.id)+".json"),ec);}
std::shared_ptr<Lyrics> projectLyrics(LyricsDocument document){auto out=std::make_shared<Lyrics>();out->provider=document.provider;for(auto& p:LyricsProviderRegistry::providers())if(p.id==document.provider)out->provider=p.name;out->format=document.format;out->recordingDuration=document.metadata.duration;out->plain=document.plain;for(auto& l:document.lines){out->lines.emplace_back(l.start,l.text);if(!out->plain.empty())out->plain+=L"\n";out->plain+=l.text;}out->preview=out->plain.substr(0,240);out->document=std::make_shared<LyricsDocument>(std::move(document));out->measure();return out;}
}
