// Generated by tools/translation/build_package.py; archive is immutable.
inline constexpr wchar_t ModelUrl[]=L"https://154-219-99-106.sslip.io/releases/winisland-translation/winisland-offline-en-zh-v1.zip";
inline constexpr char ModelHash[]="36AC65DF4BCCBF08A7A9F85C09763A65971D7D2B578D2CAA7F93371D26137B3B";
inline constexpr wchar_t ModelVersion[]=L"argos-en-zh-1.9-ct2-4.6.0-v1";
inline constexpr uint64_t ModelBytes=190450176ULL;
