"""Build the optional redistributable; never touches the mainline or user data."""
from pathlib import Path
import hashlib
import json
import shutil
import zipfile

BRANCH = Path(__file__).resolve().parents[2]
CACHE = BRANCH / 'dependency-cache/translation'
OUT = CACHE / 'portable'
OUT.mkdir(exist_ok=True)
with zipfile.ZipFile(CACHE / 'python-3.11.9-embed-amd64.zip') as z:
    z.extractall(OUT)
(OUT / 'python311._pth').write_text('python311.zip\n.\nLib/site-packages\nimport site\n')
for wheel in sorted(CACHE.glob('*.whl')):
    with zipfile.ZipFile(wheel) as z:
        z.extractall(OUT / 'Lib/site-packages')
with zipfile.ZipFile(CACHE / 'models.zip') as z:
    z.extractall(OUT / 'models')
shutil.copyfile(Path(__file__).with_name('infer.py'), OUT / 'infer.py')
crt = sorted(Path('E:/WinIslandBuildTools/VC/Redist/MSVC').glob('14.*/x64/Microsoft.VC143.CRT'))[-1]
for p in crt.glob('*.dll'):
    shutil.copyfile(p, OUT / p.name)
(OUT / 'LICENSES.txt').write_text('''WinIsland optional offline translation bundle v1 (Windows x64, CPU).
Python 3.11.9: PSF license, see LICENSE.txt. https://www.python.org
CTranslate2 4.6.0: MIT; SentencePiece 0.2.0: Apache 2.0.
NumPy 2.2.6: BSD; PyYAML 6.0.2: MIT; setuptools 80.9.0: MIT.
Their full license texts are retained in Lib/site-packages/*.dist-info.
Microsoft Visual C++ app-local runtime: Microsoft Visual Studio redistributable license.
Argos Translate en-zh and zh-en 1.9 packages, via LibreTranslate 1.9.6:
OPUS-MT by Jörg Tiedemann and Santhosh Thottingal, EAMT 2020.
Models CC-BY 4.0, https://creativecommons.org/licenses/by/4.0/
Original model readmes and metadata retained in models/en-zh and models/zh-en.
Packaging excludes Stanza; WinIsland performs bounded sentence/token splitting.
Translations can be inaccurate. No external service is contacted by infer.py.
''', encoding='utf-8')
# Include an inventory for startup completeness checks; host pins the outer archive hash.
files = {p.relative_to(OUT).as_posix(): {'bytes': p.stat().st_size, 'sha256': hashlib.file_digest(p.open('rb'), 'sha256').hexdigest()} for p in sorted(OUT.rglob('*')) if p.is_file() and p.name != 'inventory.json' and '__pycache__' not in p.parts}
(OUT / 'inventory.json').write_text(json.dumps({'version': 'argos-en-zh-1.9-ct2-4.6.0-v1', 'files': files}, indent=2), encoding='utf-8')
archive = CACHE / 'winisland-offline-en-zh-v1.zip'
with zipfile.ZipFile(archive, 'w', zipfile.ZIP_DEFLATED, compresslevel=6) as z:
    for p in sorted(OUT.rglob('*')):
        if p.is_file() and '__pycache__' not in p.parts:
            z.write(p, p.relative_to(OUT).as_posix())
manifest = {'version': 'argos-en-zh-1.9-ct2-4.6.0-v1', 'bytes': archive.stat().st_size, 'sha256': hashlib.file_digest(archive.open('rb'), 'sha256').hexdigest(), 'url': 'https://154-219-99-106.sslip.io/releases/winisland-translation/winisland-offline-en-zh-v1.zip', 'expandedBytes': sum(x['bytes'] for x in files.values()), 'languages': ['en', 'zh-Hans']}
(CACHE / 'manifest.json').write_text(json.dumps(manifest, indent=2), encoding='utf-8')
header = '// Generated by tools/translation/build_package.py; archive is immutable.\n'
header += f'inline constexpr wchar_t ModelUrl[]=L"{manifest["url"]}";\n'
header += f'inline constexpr char ModelHash[]="{manifest["sha256"].upper()}";\n'
header += f'inline constexpr wchar_t ModelVersion[]=L"{manifest["version"]}";\n'
header += f'inline constexpr uint64_t ModelBytes={manifest["bytes"]}ULL;\n'
(BRANCH / 'source/src/translation_package.h').write_text(header, encoding='utf-8')
print(json.dumps(manifest, indent=2))
