const {_electron:electron}=require('@playwright/test');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{spawn}=require('node:child_process'),crypto=require('node:crypto');
const {hostCall}=require('./dist/transport');
const root=path.resolve(__dirname,'..'),out=path.join(root,'verification','transfer-'+Date.now()),data=path.join(out,'data'),files=path.join(out,'中文 files');
fs.mkdirSync(data,{recursive:true});fs.mkdirSync(files,{recursive:true});
const results=[],sleep=ms=>new Promise(r=>setTimeout(r,ms));let core,app,connection,page;
const host=(cmd,params={})=>hostCall(connection.pipe,connection.token,cmd,params,undefined,15000);
const call=async(action,params={})=>{const r=await host('transfer.call',{action,...params});assert(r.ok,r.error);return r;};
async function check(name,fn){try{await fn();results.push({name,passed:true});}catch(e){results.push({name,passed:false,error:String(e)});}console.log(JSON.stringify(results.at(-1)));fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2));}
async function until(fn,ms=12000){const end=Date.now()+ms;while(Date.now()<end){if(await fn())return;await sleep(100);}throw Error('condition timed out');}
async function start(){for(const n of ['settings-connection.json','exit.request','ready.txt'])fs.rmSync(path.join(data,n),{force:true});core=spawn(path.join(root,'build-1.3.1alpha','WinIsland-1.3.1alpha.exe'),['--verify',data],{windowsHide:true,cwd:data});await until(()=>fs.existsSync(path.join(data,'settings-connection.json')));connection=JSON.parse(fs.readFileSync(path.join(data,'settings-connection.json')));}
async function stop(crash=false){if(crash)core.kill();else fs.writeFileSync(path.join(data,'exit.request'),'exit');if(core.exitCode===null)await new Promise(r=>core.once('exit',r));}
async function command(value){fs.writeFileSync(path.join(data,'command.txt'),value);await sleep(900);}
const state=()=>fs.readFileSync(path.join(data,'state.txt'),'utf8');
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
(async()=>{try{
 await start();
 await check('默认：音乐/消息允许；文件中转关闭',async()=>{const r=await host('settings.read');assert(r.settings.showMusic&&r.settings.showMessages);assert.equal((await call('list')).enabled,false);});
 await check('音乐关闭仅退出视觉；真实播放数据和重新开启恢复',async()=>{await command('music=play');assert(state().includes('HasMusic=True')||state().includes('HasMusic=1'));let r=await host('settings.read');assert((await host('settings.write',{revision:r.revision,patch:{showMusic:false}})).ok);await sleep(1000);assert(/HasMusic=(False|0)/.test(state()));const m=await host('media.read');assert(m.active&&m.playing);r=await host('settings.read');assert((await host('settings.write',{revision:r.revision,patch:{showMusic:true}})).ok);await sleep(1000);assert(/HasMusic=(True|1)/.test(state()));});
 await check('关闭消息清理当前及队列，hideNative 保持独立',async()=>{await command('burst');let r=await host('settings.read'),native=r.settings.hideNative;assert((await host('settings.write',{revision:r.revision,patch:{showMessages:false}})).ok);await sleep(900);r=await host('settings.read');assert.equal(r.settings.hideNative,native);await command('notice-short');fs.copyFileSync(path.join(data,'state.txt'),path.join(out,'notifications-disabled-state.txt'));assert(/Pending=0/.test(state()));});
 const txt=path.join(files,'中文 笔记.txt'),md=path.join(files,'安全.md'),unknown=path.join(files,'任意.bin');fs.writeFileSync(txt,'第一行\r\nsecond line 😀');fs.writeFileSync(md,'# 标题\n<script>throw new Error("must not run")</script>\n![remote](https://invalid.example/no.png)');fs.writeFileSync(unknown,Buffer.from([0,9,42,255]));
 const a=(await call('import',{paths:[txt,md,unknown]})).ids;
 await check('未选择模式不复制；仅中转不改变原文件',async()=>{let s=await call('list');assert(s.entries.every(e=>e.state==='pending'&&!e.saved));await call('choose',{ids:[a[0]],mode:'reference'});const e=(await call('list')).entries.find(e=>e.id===a[0]);assert.equal(e.mode,'reference');assert.equal(e.state,'ready');assert.equal(e.saved,'');assert.equal(fs.readFileSync(txt,'utf8'),'第一行\r\nsecond line 😀');});
 await check('保存副本通过大小和 SHA256 校验后发布；原文件保留',async()=>{await call('choose',{ids:[a[1],a[2]],mode:'saved'});await until(async()=>{const s=await call('list');return s.entries.filter(e=>a.slice(1).includes(e.id)).every(e=>e.state==='ready');});for(const e of (await call('list')).entries.filter(e=>a.slice(1).includes(e.id))){assert(fs.existsSync(e.original));assert.equal(hash(e.original),hash(e.saved));assert(e.saved.startsWith(path.join(data,'file-transfer','files')));}});
 await check('同路径去重；同名不同来源不覆盖',async()=>{assert.deepEqual((await call('import',{paths:[txt]})).ids,[a[0]]);const other=path.join(files,'other');fs.mkdirSync(other);fs.writeFileSync(path.join(other,'中文 笔记.txt'),'different');const b=(await call('import',{paths:[path.join(other,'中文 笔记.txt')]})).ids;assert.notEqual(b[0],a[0]);await call('choose',{ids:b,mode:'saved'});await until(async()=>(await call('list')).entries.find(e=>e.id===b[0]).state==='ready');assert.equal(fs.readFileSync(txt,'utf8'),'第一行\r\nsecond line 😀');});
 await check('失效引用标记与重新定位，不删除旧源或保存副本',async()=>{fs.renameSync(txt,txt+'.moved');await call('refresh');assert.equal((await call('list')).entries.find(e=>e.id===a[0]).state,'invalid');await call('relink',{id:a[0],path:txt+'.moved'});await call('choose',{ids:[a[0]],mode:'reference'});assert.equal((await call('list')).entries.find(e=>e.id===a[0]).state,'ready');});
 await check('启用状态、索引、正常与异常重启保持',async()=>{await call('enable',{enabled:true});let count=(await call('list')).entries.length;await stop();await start();assert.equal((await call('list')).entries.length,count);assert((await call('list')).enabled);assert.equal((await host('settings.read')).settings.showMessages,false);await stop(true);await start();assert.equal((await call('list')).entries.length,count);});
 app=await electron.launch({executablePath:path.join(root,'release/settings/WinIslandSettings.exe'),args:['--pipe='+connection.pipe,'--token='+connection.token,'--session-dir='+data],timeout:30000});page=await app.firstWindow();const errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.locator('#tab-4').click();
 await check('完整窗口覆盖，保留下层布局且停止下层输入；返回恢复',async()=>{await page.locator('#transfer-open').click();await sleep(120);const p=await page.evaluate(()=>{const layer=document.querySelector('.plugin-overlay'),r=layer.getBoundingClientRect();return {w:r.width,h:r.height,ww:innerWidth,hh:innerHeight,p:document.getElementById('panel-4').isConnected,inert:document.getElementById('content').inert};});assert(p.w>p.ww*.9&&p.h>p.hh*.9&&p.p&&p.inert,JSON.stringify(p));await sleep(700);await page.screenshot({path:path.join(out,'transfer-page.png')});await page.locator('#transfer-back').click();await sleep(750);assert.equal(await page.locator('#content').evaluate(e=>e.inert),false);assert.equal(await page.locator('.plugin-overlay').count(),0);});
 await check('快速反向转场、唯一面板、无遗留动画',async()=>{await page.evaluate(()=>document.getElementById('transfer-open').click());await sleep(100);await page.evaluate(()=>document.getElementById('transfer-back').click());await sleep(100);await page.evaluate(()=>document.getElementById('transfer-open').click());await sleep(900);assert.equal(await page.locator('.plugin-overlay').count(),1);assert.equal(await page.locator('#transfer-page').count(),1);assert.equal(await page.evaluate(()=>document.getAnimations().filter(a=>a.playState==='running').length),0);});
 await check('搜索、预览、安全 Markdown、任意文件信息；无脚本错误',async()=>{await until(async()=>await page.locator('.transfer-card').count()>=4);await page.getByRole('searchbox').fill('.md');assert.equal(await page.locator('.transfer-card:visible').count(),1);await page.locator('.transfer-card:visible').click();await until(async()=>(await page.locator('.preview-body').textContent()).includes('script'));assert.equal(await page.locator('.preview-body script,.preview-body img').count(),0);await page.getByRole('button',{name:'关闭预览',exact:true}).click();await page.getByRole('searchbox').fill('.bin');await page.locator('.transfer-card:visible').click();await until(async()=>(await page.locator('.preview-body').textContent()).includes('支持中转'));await page.screenshot({path:path.join(out,'unknown-preview.png')});assert.deepEqual(errors,[]);});
 await check('窄窗口与 reduced motion',async()=>{await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(660,580));await page.emulateMedia({reducedMotion:'reduce'});await page.getByRole('button',{name:'关闭预览',exact:true}).click();await page.getByRole('searchbox').fill('');await page.screenshot({path:path.join(out,'narrow-reduced.png')});assert.equal(await page.locator('.transfer-grid').evaluate(e=>getComputedStyle(e).gridTemplateColumns.split(' ').length),1);await page.locator('#transfer-back').click();await sleep(150);assert.equal(await page.locator('.plugin-overlay').count(),0);});
 await check('Electron 安全边界与核心真实开关保存',async()=>{const prefs=await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].webContents.getLastWebPreferences());assert(prefs.contextIsolation&&prefs.sandbox&&!prefs.nodeIntegration);await page.locator('#tab-0').click();await page.locator('#showMessages').click();await until(async()=>(await host('settings.read')).settings.showMessages===true);const r=await page.evaluate(()=>window.winIsland.call('invalid-resolve','transfer.call',{action:'resolve',id:'any'}));assert(!r.ok);});
 await app.close();app=null;
 await check('复制取消及重启未完成任务恢复',async()=>{const big=path.join(files,'large.bin');const f=fs.openSync(big,'w');fs.ftruncateSync(f,512*1024*1024);fs.closeSync(f);const ids=(await call('import',{paths:[big]})).ids;await call('choose',{ids,mode:'saved'});await call('cancel',{id:ids[0]});await until(async()=>['cancelled','failed'].includes((await call('list')).entries.find(e=>e.id===ids[0]).state),30000);assert(fs.existsSync(big));await stop();const index=path.join(data,'file-transfer/index.json'),obj=JSON.parse(fs.readFileSync(index));obj.entries.find(e=>e.id===ids[0]).state='copying';fs.writeFileSync(index,JSON.stringify(obj));await start();assert.equal((await call('list')).entries.find(e=>e.id===ids[0]).state,'cancelled');});
 }finally{if(app)await app.close();if(core?.exitCode===null)await stop();fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2));console.log('Evidence: '+out);process.exitCode=results.some(r=>!r.passed)?1:0;}})().catch(e=>{console.error(e);process.exitCode=1;});
