#include "open_runtime.h"
#include "file_drag_identity.h"
#include <imm.h>
#include <windowsx.h>
#include <d3d11.h>
#include <dxgi.h>
#include <cstring>
namespace wi {
namespace {
template<auto F>struct Gate;
template<class R,class... A,R(*F)(A...)>struct Gate<F>{static R call(A... a)noexcept{try{return F(a...);}catch(...){return WI_EXT_FAULT;}}};
bool str(const char* s,size_t n){return s&&memchr(s,0,n);}
int cppView(WiViewCallback f,void* c,WiViewEvent* e){try{return f?f(c,e):0;}catch(...){return WI_EXT_FAULT;}}
int safeView(WiViewCallback f,void* c,WiViewEvent* e){__try{return cppView(f,c,e);}__except(EXCEPTION_EXECUTE_HANDLER){return WI_EXT_FAULT;}}
int cppHook(WiHostHook f,void* c,WiHostPacket* e){try{return f(c,e);}catch(...){return WI_EXT_FAULT;}}
int safeHook(WiHostHook f,void* c,WiHostPacket* e){__try{return cppHook(f,c,e);}__except(EXCEPTION_EXECUTE_HANDLER){return WI_EXT_FAULT;}}
fs::path relativePath(const fs::path& root,const char* s){if(!str(s,32768))throw std::runtime_error("path length");fs::path rel=wide(s);if(rel.has_root_path())throw std::runtime_error("absolute path rejected");for(auto& c:rel)if(c==L".."||c.wstring().find(L':')!=std::wstring::npos)throw std::runtime_error("path traversal");auto base=fs::canonical(root),p=fs::canonical(base/rel);auto a=base.begin(),b=p.begin();for(;a!=base.end();++a,++b)if(b==p.end()||_wcsicmp(a->c_str(),b->c_str()))throw std::runtime_error("path escape");return p;}
std::wstring quote(const std::wstring& s){std::wstring out=L"\"";size_t slash=0;for(auto c:s){if(c==L'\\'){++slash;continue;}out.append(slash*(c==L'"'?2:1),L'\\');slash=0;if(c==L'"')out+=L'\\';out+=c;}out.append(slash*2,L'\\');return out+L'"';}
const GUID& dragIdentity(){return managedFileIdentity();}
CLIPFORMAT dragFormat(){return managedFileFormat();}
bool internalDrag(IDataObject* o){FORMATETC f{dragFormat(),nullptr,DVASPECT_CONTENT,-1,TYMED_HGLOBAL};STGMEDIUM m{};if(!o||FAILED(o->GetData(&f,&m)))return false;bool own=false;if(GlobalSize(m.hGlobal)>=sizeof(GUID)){auto p=(GUID*)GlobalLock(m.hGlobal);if(p){own=IsEqualGUID(*p,dragIdentity());GlobalUnlock(m.hGlobal);}}ReleaseStgMedium(&m);return own;}
std::string fileList(IDataObject* o){FORMATETC f{CF_HDROP,nullptr,DVASPECT_CONTENT,-1,TYMED_HGLOBAL};STGMEDIUM m{};if(FAILED(o->GetData(&f,&m)))return {};std::string result;auto n=DragQueryFileW((HDROP)m.hGlobal,0xffffffff,nullptr,0);if(n<=256)for(UINT i=0;i<n;++i){auto size=DragQueryFileW((HDROP)m.hGlobal,i,nullptr,0);std::wstring name(size+1,0);DragQueryFileW((HDROP)m.hGlobal,i,name.data(),size+1);name.resize(size);auto s=utf8(name);if(result.size()+s.size()+1>65536){result.clear();break;}if(!result.empty())result+='\n';result+=s;}ReleaseStgMedium(&m);return result;}
struct FilesObject:IDataObject{
 ULONG refs=1;std::vector<std::wstring> files;explicit FilesObject(const std::string& text){std::istringstream in(text);std::string s;while(std::getline(in,s))files.push_back(wide(s));}
 HRESULT STDMETHODCALLTYPE QueryInterface(REFIID id,void** p)override{if(id==IID_IUnknown||id==IID_IDataObject){*p=this;AddRef();return S_OK;}*p=nullptr;return E_NOINTERFACE;}
 ULONG STDMETHODCALLTYPE AddRef()override{return ++refs;}ULONG STDMETHODCALLTYPE Release()override{auto n=--refs;if(!n)delete this;return n;}
 HRESULT STDMETHODCALLTYPE QueryGetData(FORMATETC* f)override{return f&&(f->cfFormat==CF_HDROP||f->cfFormat==dragFormat())&&(f->tymed&TYMED_HGLOBAL)&&f->dwAspect==DVASPECT_CONTENT?S_OK:DV_E_FORMATETC;}
 HRESULT STDMETHODCALLTYPE GetData(FORMATETC* f,STGMEDIUM* out)override{if(FAILED(QueryGetData(f)))return DV_E_FORMATETC;size_t bytes=sizeof(GUID);if(f->cfFormat==CF_HDROP){bytes=sizeof(DROPFILES)+2;for(auto& s:files)bytes+=(s.size()+1)*2;}auto h=GlobalAlloc(GHND,bytes);if(!h)return E_OUTOFMEMORY;auto p=(BYTE*)GlobalLock(h);if(f->cfFormat==CF_HDROP){auto d=(DROPFILES*)p;d->pFiles=sizeof(DROPFILES);d->fWide=TRUE;auto dest=(wchar_t*)(p+sizeof(DROPFILES));for(auto& s:files){memcpy(dest,s.c_str(),(s.size()+1)*2);dest+=s.size()+1;}}else memcpy(p,&dragIdentity(),sizeof(GUID));GlobalUnlock(h);*out={TYMED_HGLOBAL};out->hGlobal=h;return S_OK;}
 HRESULT STDMETHODCALLTYPE GetDataHere(FORMATETC*,STGMEDIUM*)override{return E_NOTIMPL;}HRESULT STDMETHODCALLTYPE GetCanonicalFormatEtc(FORMATETC*,FORMATETC*)override{return E_NOTIMPL;}HRESULT STDMETHODCALLTYPE SetData(FORMATETC*,STGMEDIUM*,BOOL)override{return E_NOTIMPL;}
 HRESULT STDMETHODCALLTYPE EnumFormatEtc(DWORD dir,IEnumFORMATETC** out)override{FORMATETC f[]={{CF_HDROP,nullptr,DVASPECT_CONTENT,-1,TYMED_HGLOBAL},{dragFormat(),nullptr,DVASPECT_CONTENT,-1,TYMED_HGLOBAL}};return dir==DATADIR_GET?SHCreateStdEnumFmtEtc(2,f,out):E_NOTIMPL;}
 HRESULT STDMETHODCALLTYPE DAdvise(FORMATETC*,DWORD,IAdviseSink*,DWORD*)override{return OLE_E_ADVISENOTSUPPORTED;}HRESULT STDMETHODCALLTYPE DUnadvise(DWORD)override{return OLE_E_ADVISENOTSUPPORTED;}HRESULT STDMETHODCALLTYPE EnumDAdvise(IEnumSTATDATA**)override{return OLE_E_ADVISENOTSUPPORTED;}
};
struct FilesSource:IDropSource{
 ULONG refs=1;std::atomic<bool>* stopping;explicit FilesSource(std::atomic<bool>* p):stopping(p){}
 HRESULT STDMETHODCALLTYPE QueryInterface(REFIID id,void** p)override{if(id==IID_IUnknown||id==IID_IDropSource){*p=this;AddRef();return S_OK;}*p=nullptr;return E_NOINTERFACE;}
 ULONG STDMETHODCALLTYPE AddRef()override{return ++refs;}ULONG STDMETHODCALLTYPE Release()override{auto n=--refs;if(!n)delete this;return n;}
 HRESULT STDMETHODCALLTYPE QueryContinueDrag(BOOL esc,DWORD keys)override{return esc||*stopping?DRAGDROP_S_CANCEL:!(keys&MK_LBUTTON)?DRAGDROP_S_DROP:S_OK;}HRESULT STDMETHODCALLTYPE GiveFeedback(DWORD)override{return DRAGDROP_S_USEDEFAULTCURSORS;}
};
}
struct OpenRuntime::Owner {Impl* host;std::string id;fs::path package,data;DWORD loader;std::atomic<bool> stopping=false;};
struct OpenRuntime::Impl{
 struct View;
 struct FilesDrop:IDropTarget{
  ULONG refs=1;View* view;bool valid=false,internal=false;explicit FilesDrop(View* v):view(v){}
  HRESULT STDMETHODCALLTYPE QueryInterface(REFIID id,void** p)override{if(id==IID_IUnknown||id==IID_IDropTarget){*p=this;AddRef();return S_OK;}*p=nullptr;return E_NOINTERFACE;}
  ULONG STDMETHODCALLTYPE AddRef()override{return ++refs;}ULONG STDMETHODCALLTYPE Release()override{auto n=--refs;if(!n)delete this;return n;}
  HRESULT STDMETHODCALLTYPE DragEnter(IDataObject* o,DWORD,POINTL,DWORD* effect)override{internal=internalDrag(o);FORMATETC f{CF_HDROP,nullptr,DVASPECT_CONTENT,-1,TYMED_HGLOBAL};valid=!internal&&!view->owner->stopping&&SUCCEEDED(o->QueryGetData(&f));*effect=valid?DROPEFFECT_COPY:DROPEFFECT_NONE;return S_OK;}
  HRESULT STDMETHODCALLTYPE DragOver(DWORD,POINTL,DWORD* e)override{*e=valid&&!view->owner->stopping?DROPEFFECT_COPY:DROPEFFECT_NONE;return S_OK;}
  HRESULT STDMETHODCALLTYPE DragLeave()override{valid=internal=false;return S_OK;}
  HRESULT STDMETHODCALLTYPE Drop(IDataObject* o,DWORD,POINTL,DWORD* effect)override{*effect=DROPEFFECT_NONE;if(valid&&!internalDrag(o)&&!view->owner->stopping){auto files=fileList(o);if(!files.empty()){view->event(WI_VIEW_FILES,files.c_str());*effect=DROPEFFECT_COPY;}}valid=internal=false;return S_OK;}
 };
 struct View{
  uint64_t id;std::shared_ptr<Owner> lifetime;Owner* owner;WiViewDefinition def{};std::mutex mutex;HWND window=nullptr,child=nullptr;FilesDrop* drop=nullptr;
  RECT desired{},actual{};std::atomic<uint32_t> dpi=96;float radius=0,opacity=1;bool visible=false,lastVisible=false,close=false,focus=false;int caretX=0,caretY=0;
  std::atomic<bool> done=false,deviceLost=false;std::vector<uint8_t> frame;uint32_t fw=0,fh=0;uint64_t revision=0,painted=0;std::string drag;
  int event(uint32_t kind,const char* text=nullptr,UINT message=0,WPARAM wp=0,LPARAM lp=0){WiViewEvent e{sizeof(e),1,kind,dpi.load(),id,(uintptr_t)window,(uintptr_t)child,GET_X_LPARAM(lp),GET_Y_LPARAM(lp),actual.right-actual.left,actual.bottom-actual.top,message,wp,lp,text,0};if(kind==WI_VIEW_INPUT&&(message==WM_MOUSEWHEEL||message==WM_MOUSEHWHEEL)){POINT point{e.x,e.y};ScreenToClient(window,&point);e.x=point.x;e.y=point.y;}if(kind==WI_VIEW_FOCUS)e.flags=message==WM_SETFOCUS;if(kind==WI_VIEW_DRAG_RESULT)e.flags=(uint32_t)wp;if(kind==WI_VIEW_IME)e.flags=(uint32_t)wp;int rc=safeView(def.callback,def.context,&e);if(kind==WI_VIEW_CREATE)child=(HWND)e.nativeChild;return rc;}
  void paint(){std::vector<uint8_t> pixels;uint32_t w,h;float r,a;{std::lock_guard l(mutex);w=fw;h=fh;if(!w||!h||frame.size()!=size_t(w)*h*4)return;auto sw=w,sh=h;w=(uint32_t)std::clamp(actual.right-actual.left,1L,4096L);h=(uint32_t)std::clamp(actual.bottom-actual.top,1L,4096L);pixels.assign(size_t(w)*h*4,0);for(uint32_t y=0;y<std::min(h,sh);++y)memcpy(pixels.data()+size_t(y)*w*4,frame.data()+size_t(y)*sw*4,std::min(w,sw)*4);r=std::min(radius*dpi.load()/96.f,std::min(w,h)/2.f);a=opacity;painted=revision;}
   // Coverage only on alpha at the boundary; interior pixels/text stay unchanged.
   for(uint32_t y=0;y<h;++y)for(uint32_t x=0;x<w;++x){float dx=std::max(std::max(r-(x+.5f),(x+.5f)-(w-r)),0.f),dy=std::max(std::max(r-(y+.5f),(y+.5f)-(h-r)),0.f);float coverage=(dx>0&&dy>0)?std::clamp(r+.5f-std::sqrt(dx*dx+dy*dy),0.f,1.f):1.f;coverage*=a;if(coverage<1)for(int c=0;c<4;++c)pixels[(size_t(y)*w+x)*4+c]=(BYTE)(pixels[(size_t(y)*w+x)*4+c]*coverage);}
   HDC dc=GetDC(nullptr),mem=CreateCompatibleDC(dc);BITMAPINFO bi{};bi.bmiHeader={sizeof(BITMAPINFOHEADER),(LONG)w,-(LONG)h,1,32,BI_RGB};void* bits=nullptr;HBITMAP bmp=CreateDIBSection(dc,&bi,DIB_RGB_COLORS,&bits,nullptr,0);if(bmp){memcpy(bits,pixels.data(),pixels.size());auto old=SelectObject(mem,bmp);POINT dest{actual.left,actual.top},src{};SIZE size{(LONG)w,(LONG)h};BLENDFUNCTION blend{AC_SRC_OVER,0,255,AC_SRC_ALPHA};UpdateLayeredWindow(window,dc,&dest,&size,mem,&src,0,&blend,ULW_ALPHA);SelectObject(mem,old);DeleteObject(bmp);}DeleteDC(mem);ReleaseDC(nullptr,dc);
  }
 };
 struct Process{
  WiProcess id;Owner* owner;HANDLE process=nullptr,job=nullptr,input=nullptr,output=nullptr;DWORD pid=0,timeout=2000;
  std::thread reader,writer;std::mutex mutex;std::condition_variable cv;std::deque<std::vector<uint8_t>> incoming,outgoing;
  std::atomic<bool> stopping=false,readDone=false,writeDone=false;std::atomic<uint64_t> received=0,dropped=0;std::atomic<double> stopAt=0;bool killed=false;
  ~Process(){if(reader.joinable())reader.join();if(writer.joinable())writer.join();for(auto h:{process,job,input,output})if(h)CloseHandle(h);}
  void stop(){std::lock_guard l(mutex);if(!stopping){stopAt=now();stopping=true;outgoing.clear();outgoing.push_back({});cv.notify_all();}}
  bool exited(){return WaitForSingleObject(process,0)==WAIT_OBJECT_0;}
  void poll(){if(stopping&&!exited()&&now()-stopAt.load()>timeout/1000.){TerminateJobObject(job,ERROR_CANCELLED);killed=true;}if(exited()){if(reader.joinable())CancelSynchronousIo(reader.native_handle());if(writer.joinable())CancelSynchronousIo(writer.native_handle());cv.notify_all();}}
  void run(){reader=std::thread([this]{auto read=[&](void* p,DWORD n){auto b=(BYTE*)p;while(n){DWORD got=0;if(!ReadFile(output,b,n,&got,nullptr)||!got)return false;b+=got;n-=got;}return true;};for(;;){uint32_t n;if(!read(&n,4)||n>1024*1024)break;std::vector<uint8_t> data(n);if(n&&!read(data.data(),n))break;std::lock_guard l(mutex);if(incoming.size()>=32){++dropped;incoming.pop_front();}incoming.push_back(std::move(data));++received;}readDone=true;});
   writer=std::thread([this]{for(;;){std::vector<uint8_t> data;{std::unique_lock l(mutex);cv.wait_for(l,std::chrono::milliseconds(50),[&]{return !outgoing.empty()||exited();});if(exited())break;if(outgoing.empty())continue;data=std::move(outgoing.front());outgoing.pop_front();}auto write=[&](const void* p,DWORD n){auto b=(const BYTE*)p;while(n){DWORD wrote=0;if(!WriteFile(input,b,n,&wrote,nullptr)||!wrote)return false;b+=wrote;n-=wrote;}return true;};uint32_t n=(uint32_t)data.size();if(!write(&n,4)||(n&&!write(data.data(),n)))break;}writeDone=true;});
  }
 };
 struct Hook{WiHook id;Owner* owner;WiHostHookDefinition def;};
 std::mutex mutex;std::atomic<uint64_t> hookRevision=0,uiEpoch=0;uint64_t next=1;std::vector<std::shared_ptr<Owner>> owners;std::map<WiView,std::shared_ptr<View>> views;std::map<WiProcess,std::shared_ptr<Process>> processes;std::vector<Hook> hooks;
 std::deque<WiHostPacket> queue,results;std::atomic<bool> stopping=false;std::thread ui;DWORD uiId=0;std::condition_variable ready;
 std::mutex gpuMutex;ComPtr<ID3D11Device> gpu;ComPtr<ID3D11DeviceContext> gpuContext;ComPtr<ID3D11Texture2D> gpuStaging;uint32_t gpuWidth=0,gpuHeight=0;
 Impl(){ui=std::thread([this]{uiLoop();});std::unique_lock l(mutex);ready.wait(l,[&]{return uiId!=0;});}
 ~Impl(){stopping=true;ui.join();for(auto& [id,p]:processes)p->stop();for(;;){bool done=true;for(auto& [id,p]:processes){p->poll();done&=p->exited()&&p->readDone&&p->writeDone;}if(done)break;Sleep(10);}}
 static int check(Owner& o,bool loader=false){if(loader&&GetCurrentThreadId()!=o.loader)return WI_EXT_THREAD;return o.stopping?WI_EXT_STOPPED:0;}
 static LRESULT CALLBACK proc(HWND h,UINT m,WPARAM w,LPARAM l){auto v=(View*)GetWindowLongPtrW(h,GWLP_USERDATA);if(m==WM_NCCREATE){v=(View*)((CREATESTRUCTW*)l)->lpCreateParams;SetWindowLongPtrW(h,GWLP_USERDATA,(LONG_PTR)v);v->window=h;}if(!v)return DefWindowProcW(h,m,w,l);
  if(m==WM_CLOSE)return 0;if(m==WM_ERASEBKGND)return 1;if(v->owner->stopping)return DefWindowProcW(h,m,w,l);
  if(m==WM_SETFOCUS||m==WM_KILLFOCUS){v->event(WI_VIEW_FOCUS,nullptr,m);if(m==WM_SETFOCUS&&v->child)SetFocus(v->child);}
  if(m==WM_IME_COMPOSITION){HIMC im=ImmGetContext(h);if(im){for(auto kind:{GCS_COMPSTR,GCS_RESULTSTR})if(l&kind){LONG n=ImmGetCompositionStringW(im,kind,nullptr,0);if(n>0&&n<=65536){std::wstring text(n/2,0);ImmGetCompositionStringW(im,kind,text.data(),n);auto s=utf8(text);v->event(WI_VIEW_IME,s.c_str(),m,kind==GCS_RESULTSTR?1:0);}}ImmReleaseContext(h,im);}}
  if((m>=WM_MOUSEFIRST&&m<=WM_MOUSELAST)||(m>=WM_KEYFIRST&&m<=WM_KEYLAST)){if(m==WM_LBUTTONDOWN){SetFocus(h);SetCapture(h);}if(m==WM_LBUTTONUP||m==WM_CAPTURECHANGED)ReleaseCapture();if(v->event(WI_VIEW_INPUT,nullptr,m,w,l)>0)return 0;}
  return DefWindowProcW(h,m,w,l);
 }
 void uiLoop(){OleInitialize(nullptr);SetThreadDpiAwarenessContext(DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2);WNDCLASSW wc{};wc.lpfnWndProc=proc;wc.hInstance=GetModuleHandleW(nullptr);wc.hCursor=LoadCursorW(nullptr,IDC_ARROW);wc.hbrBackground=(HBRUSH)GetStockObject(BLACK_BRUSH);wc.lpszClassName=L"WinIsland.CommunityView.v1";RegisterClassW(&wc);{std::lock_guard l(mutex);uiId=GetCurrentThreadId();}ready.notify_all();
  for(;;){MSG msg;while(PeekMessageW(&msg,nullptr,0,0,PM_REMOVE)){TranslateMessage(&msg);DispatchMessageW(&msg);}std::vector<std::shared_ptr<View>> list;{std::lock_guard l(mutex);for(auto& [id,v]:views)list.push_back(v);}for(auto& v:list){bool close,visible,focus;int caretX,caretY;RECT rect;std::string drag;{std::lock_guard l(v->mutex);close=v->close||v->owner->stopping||stopping;visible=v->visible;rect=v->desired;focus=std::exchange(v->focus,false);drag.swap(v->drag);caretX=v->caretX;caretY=v->caretY;}
    if(v->done)continue;if(v->deviceLost.exchange(false)&&!close)v->event(WI_VIEW_DEVICE_LOST);if(close){v->event(WI_VIEW_DESTROY);if(v->window){ShowWindow(v->window,SW_HIDE);if(v->drop){RevokeDragDrop(v->window);v->drop->Release();v->drop=nullptr;}if(v->child&&IsWindow(v->child))DestroyWindow(v->child);DestroyWindow(v->window);v->window=nullptr;}v->done=true;continue;}
    if(!v->window){v->actual=rect;auto ex=WS_EX_TOPMOST|WS_EX_TOOLWINDOW|(v->def.kind==WI_VIEW_PIXELS?WS_EX_LAYERED:0);v->window=CreateWindowExW(ex,wc.lpszClassName,wide(v->owner->id).c_str(),WS_POPUP,rect.left,rect.top,std::max(1L,rect.right-rect.left),std::max(1L,rect.bottom-rect.top),nullptr,nullptr,wc.hInstance,v.get());if(!v->window){v->event(WI_VIEW_DESTROY);v->done=true;continue;}int rc=v->event(WI_VIEW_CREATE);if(rc<0||(v->def.kind==WI_VIEW_NATIVE&&v->child&&(!IsWindow(v->child)||GetParent(v->child)!=v->window))){std::lock_guard l(v->mutex);v->close=true;continue;}if(v->def.flags&1){v->drop=new FilesDrop(v.get());RegisterDragDrop(v->window,v->drop);}}
    bool layout=memcmp(&rect,&v->actual,sizeof(rect))!=0;if(layout){v->actual=rect;SetWindowPos(v->window,HWND_TOPMOST,rect.left,rect.top,std::max(1L,rect.right-rect.left),std::max(1L,rect.bottom-rect.top),SWP_NOACTIVATE);if(v->child)MoveWindow(v->child,0,0,rect.right-rect.left,rect.bottom-rect.top,TRUE);v->event(WI_VIEW_LAYOUT);}
    if(visible!=v->lastVisible){v->lastVisible=visible;ShowWindow(v->window,visible?SW_SHOWNOACTIVATE:SW_HIDE);if(!visible)v->event(WI_VIEW_HIDDEN);else v->event(WI_VIEW_LAYOUT);}
    if(visible&&focus){SetForegroundWindow(v->window);SetFocus(v->child?v->child:v->window);HIMC im=ImmGetContext(v->window);if(im){COMPOSITIONFORM form{CFS_POINT,{caretX,caretY}};ImmSetCompositionWindow(im,&form);CANDIDATEFORM candidate{0,CFS_CANDIDATEPOS,{caretX,caretY}};ImmSetCandidateWindow(im,&candidate);ImmReleaseContext(v->window,im);}}
    if(visible&&v->def.kind==WI_VIEW_PIXELS){bool paint;{std::lock_guard l(v->mutex);paint=v->revision!=v->painted||layout;}if(paint)v->paint();}
    if(!drag.empty()&&!v->owner->stopping){auto object=new FilesObject(drag);auto source=new FilesSource(&v->owner->stopping);DWORD effect=0;DoDragDrop(object,source,DROPEFFECT_COPY,&effect);source->Release();object->Release();if(!v->owner->stopping)v->event(WI_VIEW_DRAG_RESULT,nullptr,0,effect);}
   }
   ++uiEpoch;if(stopping){bool done=true;for(auto& v:list)done&=v->done.load();if(done)break;}MsgWaitForMultipleObjects(0,nullptr,FALSE,16,QS_ALLINPUT);
  }OleUninitialize();
 }
 static int create(void* c,const WiViewDefinition* d,WiView* out){auto& o=*(Owner*)c;int rc=check(o,true);if(rc)return rc;if(!d||d->size<sizeof(*d)||d->version!=1)return WI_EXT_VERSION;if(!out||!d->element||!d->callback||(d->kind!=1&&d->kind!=2)||d->flags>1)return WI_EXT_INVALID;auto& h=*o.host;std::lock_guard l(h.mutex);std::erase_if(h.views,[](auto& p){return p.second->done.load();});if(h.views.size()>=32)return WI_EXT_LIMIT;auto v=std::make_shared<View>();v->id=h.next++;v->owner=&o;v->lifetime=*std::find_if(h.owners.begin(),h.owners.end(),[&](auto& x){return x.get()==&o;});v->def=*d;h.views[v->id]=v;*out=v->id;return 0;}
 static std::shared_ptr<View> view(Owner& o,WiView id){std::lock_guard l(o.host->mutex);auto it=o.host->views.find(id);return it==o.host->views.end()||it->second->owner!=&o||it->second->done?nullptr:it->second;}
 static int close(void* c,WiView id){auto& o=*(Owner*)c;auto v=view(o,id);if(!v)return WI_EXT_NOT_FOUND;std::lock_guard l(v->mutex);v->close=true;return 0;}
 static int frame(void* c,WiView id,const WiViewFrame* f){auto& o=*(Owner*)c;int rc=check(o);if(rc)return rc;if(!f||f->size<sizeof(*f)||f->version!=1)return WI_EXT_VERSION;if(!f->bgra||!f->width||!f->height||f->width>4096||f->height>4096||f->stride<f->width*4||uint64_t(f->stride)*f->height>f->bytes)return WI_EXT_INVALID;auto v=view(o,id);if(!v||v->def.kind!=WI_VIEW_PIXELS)return WI_EXT_NOT_FOUND;std::lock_guard l(v->mutex);if(o.stopping||v->close)return WI_EXT_STOPPED;v->fw=f->width;v->fh=f->height;v->frame.resize(size_t(f->width)*f->height*4);for(uint32_t y=0;y<f->height;++y)memcpy(v->frame.data()+size_t(y)*f->width*4,(const BYTE*)f->bgra+size_t(y)*f->stride,f->width*4);++v->revision;return 0;}
 static int texture(void* c,WiView id,const WiSharedTexture* t){auto& o=*(Owner*)c;int rc=check(o);if(rc)return rc;if(!t||t->size<sizeof(*t)||t->version!=1)return WI_EXT_VERSION;if(!t->handle)return WI_EXT_INVALID;auto& h=*o.host;std::lock_guard l(h.gpuMutex);if(!h.gpu){auto hr=D3D11CreateDevice(nullptr,D3D_DRIVER_TYPE_HARDWARE,nullptr,D3D11_CREATE_DEVICE_BGRA_SUPPORT,nullptr,0,D3D11_SDK_VERSION,&h.gpu,nullptr,&h.gpuContext);if(FAILED(hr))return WI_EXT_UNSUPPORTED;}
  ComPtr<ID3D11Texture2D> src;HRESULT hr=h.gpu->OpenSharedResource((HANDLE)t->handle,IID_PPV_ARGS(&src));if(FAILED(hr))return WI_EXT_INVALID;D3D11_TEXTURE2D_DESC d{};src->GetDesc(&d);if(d.Format!=DXGI_FORMAT_B8G8R8A8_UNORM||d.Width>4096||d.Height>4096||d.SampleDesc.Count!=1||d.ArraySize!=1||d.MipLevels!=1)return WI_EXT_INVALID;ComPtr<IDXGIKeyedMutex> keyed;if(FAILED(src.As(&keyed)))return WI_EXT_INVALID;hr=keyed->AcquireSync(t->acquireKey,0);if(hr!=S_OK)return WI_EXT_BUSY;
  d.Usage=D3D11_USAGE_STAGING;d.BindFlags=0;d.MiscFlags=0;d.CPUAccessFlags=D3D11_CPU_ACCESS_READ;if(!h.gpuStaging||h.gpuWidth!=d.Width||h.gpuHeight!=d.Height){h.gpuStaging.Reset();hr=h.gpu->CreateTexture2D(&d,nullptr,&h.gpuStaging);h.gpuWidth=d.Width;h.gpuHeight=d.Height;}if(SUCCEEDED(hr))h.gpuContext->CopyResource(h.gpuStaging.Get(),src.Get());keyed->ReleaseSync(t->releaseKey);if(FAILED(hr))return WI_EXT_FAULT;D3D11_MAPPED_SUBRESOURCE map{};hr=h.gpuContext->Map(h.gpuStaging.Get(),0,D3D11_MAP_READ,0,&map);if(FAILED(hr)){h.gpuStaging.Reset();h.gpuContext.Reset();h.gpu.Reset();auto v=view(o,id);if(v){std::lock_guard lock(v->mutex);v->deviceLost=true;}return WI_EXT_FAULT;}WiViewFrame f{sizeof(f),1,d.Width,d.Height,map.RowPitch,map.pData,map.RowPitch*d.Height};rc=frame(c,id,&f);h.gpuContext->Unmap(h.gpuStaging.Get(),0);return rc;
 }
 static int focus(void* c,WiView id,int32_t x,int32_t y){auto& o=*(Owner*)c;int rc=check(o);if(rc)return rc;auto v=view(o,id);if(!v)return WI_EXT_NOT_FOUND;std::lock_guard l(v->mutex);if(o.stopping||v->close)return WI_EXT_STOPPED;v->focus=true;v->caretX=x;v->caretY=y;return 0;}
 static int drag(void* c,WiView id,const char* paths){auto& o=*(Owner*)c;int rc=check(o);if(rc)return rc;if(!str(paths,65537))return WI_EXT_LIMIT;std::istringstream in(paths);std::string s;size_t n=0;while(std::getline(in,s)){auto p=fs::path(wide(s));if(!p.is_absolute()||!fs::is_regular_file(p)||++n>256)return WI_EXT_INVALID;}if(!n)return WI_EXT_INVALID;auto v=view(o,id);if(!v)return WI_EXT_NOT_FOUND;std::lock_guard l(v->mutex);if(o.stopping||v->close)return WI_EXT_STOPPED;if(!v->drag.empty())return WI_EXT_BUSY;v->drag=paths;return 0;}
 static std::shared_ptr<Process> process(Owner& o,WiProcess id){std::lock_guard l(o.host->mutex);auto it=o.host->processes.find(id);return it==o.host->processes.end()||it->second->owner!=&o?nullptr:it->second;}
 static int startProcess(void* c,const WiProcessDefinition* d,WiProcess* out){auto& o=*(Owner*)c;int rc=check(o);if(rc)return rc;if(!d||d->size<sizeof(*d)||d->version!=1)return WI_EXT_VERSION;if(!out||!str(d->arguments,8192)||d->shutdownTimeoutMs<100||d->shutdownTimeoutMs>10000)return WI_EXT_INVALID;auto executable=relativePath(o.package,d->executable);if(_wcsicmp(executable.extension().c_str(),L".exe"))return WI_EXT_INVALID;DWORD binary=0;if(!GetBinaryTypeW(executable.c_str(),&binary)||binary!=SCS_64BIT_BINARY){writeAtomic(o.data/L"process-error.txt","Expected Windows x64 helper EXE; Win32="+std::to_string(GetLastError()));return WI_EXT_UNSUPPORTED;}
  auto& h=*o.host;std::unique_lock lock(h.mutex);if(o.stopping)return WI_EXT_STOPPED;if(h.processes.size()>=32)return WI_EXT_LIMIT;auto p=std::make_shared<Process>();p->owner=&o;p->id=h.next++;p->timeout=d->shutdownTimeoutMs;auto dir=o.data/L"helper";fs::create_directories(dir/L"temp");
  SECURITY_ATTRIBUTES sa{sizeof(sa),nullptr,TRUE};HANDLE childIn=nullptr,childOut=nullptr;auto cleanup=[&]{if(childIn)CloseHandle(childIn);if(childOut)CloseHandle(childOut);};if(!CreatePipe(&childIn,&p->input,&sa,0)||!CreatePipe(&p->output,&childOut,&sa,0)){cleanup();return WI_EXT_FAULT;}SetHandleInformation(p->input,HANDLE_FLAG_INHERIT,0);SetHandleInformation(p->output,HANDLE_FLAG_INHERIT,0);HANDLE err=CreateFileW((dir/L"stderr.log").c_str(),FILE_APPEND_DATA,FILE_SHARE_READ|FILE_SHARE_WRITE,&sa,OPEN_ALWAYS,FILE_ATTRIBUTE_NORMAL,nullptr);if(err==INVALID_HANDLE_VALUE){cleanup();return WI_EXT_FAULT;}
  SIZE_T size=0;InitializeProcThreadAttributeList(nullptr,1,0,&size);std::vector<BYTE> storage(size);auto attrs=(LPPROC_THREAD_ATTRIBUTE_LIST)storage.data();InitializeProcThreadAttributeList(attrs,1,0,&size);HANDLE handles[]={childIn,childOut,err};if(!UpdateProcThreadAttribute(attrs,0,PROC_THREAD_ATTRIBUTE_HANDLE_LIST,handles,sizeof(handles),nullptr,nullptr)){DeleteProcThreadAttributeList(attrs);CloseHandle(err);cleanup();return WI_EXT_FAULT;}
  p->job=CreateJobObjectW(nullptr,nullptr);JOBOBJECT_EXTENDED_LIMIT_INFORMATION limit{};limit.BasicLimitInformation.LimitFlags=JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE;if(!p->job||!SetInformationJobObject(p->job,JobObjectExtendedLimitInformation,&limit,sizeof(limit))){CloseHandle(err);DeleteProcThreadAttributeList(attrs);cleanup();return WI_EXT_FAULT;}STARTUPINFOEXW si{};si.StartupInfo.cb=sizeof(si);si.StartupInfo.dwFlags=STARTF_USESTDHANDLES|STARTF_USESHOWWINDOW;si.StartupInfo.wShowWindow=SW_HIDE;si.StartupInfo.hStdInput=childIn;si.StartupInfo.hStdOutput=childOut;si.StartupInfo.hStdError=err;si.lpAttributeList=attrs;
  auto env=childEnvironment(dir);auto args=quote(executable.wstring())+L" "+wide(d->arguments);PROCESS_INFORMATION pi{};BOOL ok=CreateProcessW(executable.c_str(),args.data(),nullptr,nullptr,TRUE,CREATE_NO_WINDOW|CREATE_SUSPENDED|CREATE_UNICODE_ENVIRONMENT|EXTENDED_STARTUPINFO_PRESENT,env.data(),dir.c_str(),&si.StartupInfo,&pi);DeleteProcThreadAttributeList(attrs);CloseHandle(err);cleanup();if(!ok){writeAtomic(o.data/L"process-error.txt","CreateProcess failed; Win32="+std::to_string(GetLastError()));return WI_EXT_FAULT;}p->process=pi.hProcess;p->pid=pi.dwProcessId;if(!AssignProcessToJobObject(p->job,p->process)){TerminateProcess(p->process,1);CloseHandle(pi.hThread);return WI_EXT_FAULT;}ResumeThread(pi.hThread);CloseHandle(pi.hThread);p->run();h.processes[p->id]=p;*out=p->id;return 0;
 }
 static int send(void* c,WiProcess id,const void* data,uint32_t n){auto& o=*(Owner*)c;int rc=check(o);if(rc)return rc;if(!n||n>1024*1024||!data)return WI_EXT_INVALID;auto p=process(o,id);if(!p)return WI_EXT_NOT_FOUND;if(p->stopping||p->exited())return WI_EXT_STOPPED;std::lock_guard l(p->mutex);if(o.stopping||p->stopping)return WI_EXT_STOPPED;if(p->outgoing.size()>=32)return WI_EXT_LIMIT;p->outgoing.emplace_back((const BYTE*)data,(const BYTE*)data+n);p->cv.notify_one();return 0;}
 static int receive(void* c,WiProcess id,void* out,uint32_t cap,uint32_t* n){auto& o=*(Owner*)c;if(!n||(cap&&!out))return WI_EXT_INVALID;auto p=process(o,id);if(!p)return WI_EXT_NOT_FOUND;std::lock_guard l(p->mutex);if(p->incoming.empty()){*n=0;return p->exited()?WI_EXT_STOPPED:WI_EXT_NOT_READY;}*n=(uint32_t)p->incoming.front().size();if(cap<*n)return WI_EXT_LIMIT;if(*n)memcpy(out,p->incoming.front().data(),*n);p->incoming.pop_front();return 0;}
 static int info(void* c,WiProcess id,WiProcessInfo* out){auto& o=*(Owner*)c;if(!out||out->size<sizeof(*out)||out->version!=1)return WI_EXT_VERSION;auto p=process(o,id);if(!p)return WI_EXT_NOT_FOUND;DWORD code=STILL_ACTIVE;GetExitCodeProcess(p->process,&code);*out={sizeof(*out),1,p->exited()?3u:p->stopping?2u:1u,code,p->pid,p->received,p->dropped};return 0;}
 static int stopProcess(void* c,WiProcess id){auto p=process(*(Owner*)c,id);if(!p)return WI_EXT_NOT_FOUND;p->stop();return 0;}
 static int barrier(void* c,uint64_t* ticket){if(!ticket)return WI_EXT_INVALID;*ticket=((Owner*)c)->host->uiEpoch.load()+1;return 0;}
 static int barrierReady(void* c,uint64_t ticket){return ticket&&((Owner*)c)->host->uiEpoch.load()>=ticket?0:WI_EXT_NOT_READY;}
 static int releaseProcess(void* c,WiProcess id){auto& o=*(Owner*)c;auto p=process(o,id);if(!p)return WI_EXT_NOT_FOUND;if(!p->exited()||!p->readDone||!p->writeDone)return WI_EXT_BUSY;std::lock_guard lock(o.host->mutex);o.host->processes.erase(id);return 0;}
 static int hook(void* c,const WiHostHookDefinition* d,WiHook* out){auto& o=*(Owner*)c;int rc=check(o,true);if(rc)return rc;if(!d||d->size<sizeof(*d)||d->version!=1)return WI_EXT_VERSION;if(!out||!d->callback||d->topic<1||d->topic>4)return WI_EXT_INVALID;auto& h=*o.host;std::lock_guard l(h.mutex);if(h.hooks.size()>=256)return WI_EXT_LIMIT;*out=h.next++;h.hooks.push_back({*out,&o,*d});++h.hookRevision;return 0;}
 static int remove(void* c,WiHook id){auto& o=*(Owner*)c;if(GetCurrentThreadId()!=o.loader)return WI_EXT_THREAD;std::lock_guard l(o.host->mutex);++o.host->hookRevision;return std::erase_if(o.host->hooks,[&](auto& p){return p.owner==&o&&p.id==id;})?0:WI_EXT_NOT_FOUND;}
 static bool valid(const WiHostPacket& p){if(p.size<sizeof(p)||p.version!=1||p.topic<1||p.topic>4||!memchr(p.title,0,sizeof(p.title))||!memchr(p.detail,0,sizeof(p.detail))||!memchr(p.extra,0,sizeof(p.extra)))return false;for(auto n:p.number)if(!std::isfinite(n))return false;return true;}
 static int submit(void* c,const WiHostPacket* p){auto& o=*(Owner*)c;int rc=check(o);if(rc)return rc;if(!p||!valid(*p))return WI_EXT_INVALID;std::lock_guard l(o.host->mutex);if(o.stopping)return WI_EXT_STOPPED;if(o.host->queue.size()>=256)return WI_EXT_LIMIT;auto copy=*p;strcpy_s(copy.source,o.id.c_str());copy.sequence=0;o.host->queue.push_back(copy);return 0;}
 static void stopOwner(void* c){auto& o=*(Owner*)c;o.stopping=true;++o.host->hookRevision;std::lock_guard l(o.host->mutex);std::erase_if(o.host->hooks,[&](auto& h){return h.owner==&o;});std::erase_if(o.host->queue,[&](auto& p){return p.source==o.id;});std::erase_if(o.host->results,[&](auto& p){return p.source==o.id;});for(auto& [id,p]:o.host->processes)if(p->owner==&o)p->stop();}
 static int joined(void* c){auto& o=*(Owner*)c;std::lock_guard l(o.host->mutex);for(auto& [id,v]:o.host->views)if(v->owner==&o&&!v->done)return 0;for(auto& [id,p]:o.host->processes)if(p->owner==&o&&(!p->exited()||!p->readDone||!p->writeDone))return 0;return 1;}
};
uint64_t OpenRuntime::revision()const{return impl->hookRevision.load();}
OpenRuntime::OpenRuntime():impl(std::make_unique<Impl>()){}OpenRuntime::~OpenRuntime()=default;
std::shared_ptr<OpenRuntime::Owner> OpenRuntime::owner(std::string id,const fs::path& package,const fs::path& data){auto p=std::make_shared<Owner>();p->host=impl.get();p->id=std::move(id);p->package=package;p->data=data;p->loader=GetCurrentThreadId();std::lock_guard l(impl->mutex);impl->owners.push_back(p);return p;}
WiOpenApi OpenRuntime::api(Owner& o){return {sizeof(WiOpenApi),1,&o,Gate<Impl::create>::call,Gate<Impl::close>::call,Gate<Impl::frame>::call,Gate<Impl::texture>::call,Gate<Impl::focus>::call,Gate<Impl::drag>::call,Gate<Impl::startProcess>::call,Gate<Impl::send>::call,Gate<Impl::receive>::call,Gate<Impl::info>::call,Gate<Impl::stopProcess>::call,Gate<Impl::hook>::call,Gate<Impl::remove>::call,Gate<Impl::submit>::call,Gate<Impl::releaseProcess>::call,Gate<Impl::barrier>::call,Gate<Impl::barrierReady>::call};}
WiExternalLifetime OpenRuntime::lifetime(Owner& o){return {sizeof(WiExternalLifetime),1,&o,Impl::stopOwner,Impl::joined};}
void OpenRuntime::retire(Owner& o){if(!Impl::joined(&o))return;std::lock_guard l(impl->mutex);std::erase_if(impl->views,[&](auto& p){return p.second->owner==&o&&p.second->done;});std::erase_if(impl->processes,[&](auto& p){return p.second->owner==&o;});std::erase_if(impl->owners,[&](auto& p){return p.get()==&o;});}
void OpenRuntime::layout(HWND host,float scale,float islandWidth,const std::vector<SceneNode>& nodes){RECT window{},client{};GetWindowRect(host,&window);GetClientRect(host,&client);window.left+=(LONG)std::lround((client.right-islandWidth*scale)/2);std::lock_guard lock(impl->mutex);for(auto& [id,v]:impl->views){std::lock_guard l(v->mutex);auto n=std::find_if(nodes.begin(),nodes.end(),[&](auto& node){return node.id==v->def.element&&node.owner==v->owner->id;});v->visible=n!=nodes.end()&&IsWindowVisible(host);if(n!=nodes.end()){auto info=n->info();v->desired={window.left+(LONG)std::lround(info.x*scale),window.top+(LONG)std::lround(info.y*scale),window.left+(LONG)std::lround((info.x+info.width)*scale),window.top+(LONG)std::lround((info.y+info.height)*scale)};v->dpi=(uint32_t)std::lround(96*scale);v->radius=(float)n->n(WI_RADIUS);v->opacity=(float)n->n(WI_OPACITY,0,1);}}}
WiHostPacket OpenRuntime::route(WiHostPacket packet){if(!Impl::valid(packet))return {};std::vector<Impl::Hook> list;{std::lock_guard l(impl->mutex);list=impl->hooks;}std::stable_sort(list.begin(),list.end(),[](auto& a,auto& b){return a.def.priority!=b.def.priority?a.def.priority>b.def.priority:a.owner->id<b.owner->id;});for(auto& h:list)if(!h.owner->stopping&&h.def.topic==packet.topic){bool live;{std::lock_guard l(impl->mutex);live=std::any_of(impl->hooks.begin(),impl->hooks.end(),[&](auto& p){return p.id==h.id;});}if(!live)continue;auto changed=packet;int rc=safeHook(h.def.callback,h.def.context,&changed);if(rc<0){writeAtomic(h.owner->data/L"hook-error.txt","Hook callback failed, id="+std::to_string(h.id)+" code="+std::to_string(rc));continue;}if(rc==WI_HOOK_CONSUME){packet.flags|=0x80000000u;break;}if(rc==WI_HOOK_REPLACE&&Impl::valid(changed)&&changed.topic==packet.topic){changed.sequence=packet.sequence;strcpy_s(changed.source,packet.source);packet=changed;}}return packet;}
bool OpenRuntime::enqueue(WiHostPacket packet){if(!Impl::valid(packet))return false;std::lock_guard l(impl->mutex);if(impl->queue.size()>=256)return false;impl->queue.push_back(packet);return true;}
void OpenRuntime::pump(){std::vector<std::shared_ptr<Impl::Process>> processes;std::deque<WiHostPacket> q;{std::lock_guard l(impl->mutex);for(auto& [id,p]:impl->processes)processes.push_back(p);q.swap(impl->queue);}for(auto& p:processes)p->poll();for(auto& p:q){auto result=route(p);std::lock_guard l(impl->mutex);if(impl->results.size()>=256)impl->results.pop_front();impl->results.push_back(result);}}
std::vector<WiHostPacket> OpenRuntime::take(){std::lock_guard l(impl->mutex);std::vector<WiHostPacket> r;for(auto& p:impl->results)if(!strcmp(p.source,"host")||std::any_of(impl->owners.begin(),impl->owners.end(),[&](auto& o){return !o->stopping&&o->id==p.source;}))r.push_back(p);impl->results.clear();return r;}
#include "open_runtime_tests.inc"
}
