cmake_minimum_required(VERSION 3.24)
project(WinIslandLyricHelper LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_AUTOMOC ON)
set(CRYPTOPP_BUILD_TESTING OFF CACHE BOOL "" FORCE)
set(CRYPTOPP_BUILD_DOCUMENTATION OFF CACHE BOOL "" FORCE)
set(CRYPTOPP_SOURCES "${CMAKE_CURRENT_SOURCE_DIR}/../third_party/cryptopp" CACHE PATH "" FORCE)
set(QCLOUDMUSICAPI_BUILD_SHARED OFF)
add_subdirectory(../third_party/QCloudMusicApi/3rdparty/cryptopp-cmake cryptopp-build)
add_subdirectory(../third_party/QCloudMusicApi/QCloudMusicApi qcloud-build)
find_package(Qt6 REQUIRED COMPONENTS Core Network)
add_executable(WinIsland-LyricHelper main.cpp)
target_include_directories(WinIsland-LyricHelper PRIVATE ../third_party/QCloudMusicApi/QCloudMusicApi)
target_link_libraries(WinIsland-LyricHelper PRIVATE QCloudMusicApi Qt6::Core Qt6::Network)
target_compile_options(WinIsland-LyricHelper PRIVATE /utf-8)
