const {chromium}=require('@playwright/test');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{spawn}=require('node:child_process');
const {hostCall}=require('./dist/transport');
const root=path.resolve(__dirname,'..'),out=path.join(root,'verification','open-live'),data=path.join(out,'run-'+Date.now());
fs.mkdirSync(path.join(data,'mods'),{recursive:true});
for(const id of ['open-stream','open-stream-view','open-browser','open-hooks','open-process','open-lifecycle']){fs.copyFileSync(path.join(root,'open-examples/packages',id+'.wimod'),path.join(data,'mods',id+'.wimod'));fs.mkdirSync(path.join(data,'mods',id),{recursive:true});fs.writeFileSync(path.join(data,'mods',id,'host-state.txt'),'disabled');}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));async function until(fn,name,ms=20000){const end=Date.now()+ms;do{if(await fn())return;await sleep(40);}while(Date.now()<end);throw Error('timeout: '+name);}
let core,cdp,c;const checks=[];const ok=name=>{checks.push(name);console.log('PASS '+name);};
const host=(cmd,p={})=>hostCall(c.pipe,c.token,cmd,p,undefined,15000);
const list=()=>host('mods.list');const mod=async id=>(await list()).mods.find(m=>m.id===id);
async function action(op,id,cascade=false){await host('mods.action',{action:op,id,cascade});await until(async()=>!(await list()).busy,op+' '+id);}
async function command(text){fs.writeFileSync(path.join(data,'command.txt'),text);await until(()=>!fs.existsSync(path.join(data,'command.txt')),'command '+text);await sleep(80);}
const state=()=>fs.existsSync(path.join(data,'state.txt'))?fs.readFileSync(path.join(data,'state.txt'),'utf8'):'';
const media=()=>{const line=state().split('\n').find(x=>x.startsWith('Media=')&&x.includes(',open-stream-view,'));return line?line.slice(6).trim().split(','):null;};
async function control(value){const r=(await list()).resources.find(x=>x.owner==='open-stream-view'&&x.key==='stream-control');assert(r,'stream control registered');await host('mods.invoke',{handle:r.handle,value});await sleep(160);}
async function capture(name){await command('capture');fs.copyFileSync(path.join(data,'capture.png'),path.join(out,name+'.png'));}
(async()=>{try{
 core=spawn(path.join(root,'build-open-runtime/WinIsland-1.3.2alpha.exe'),['--verify',data],{cwd:data,windowsHide:true,env:{...process.env,WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS:'--remote-debugging-port=19322 --remote-debugging-address=127.0.0.1'}});
 await until(()=>fs.existsSync(path.join(data,'settings-connection.json')),'core IPC ready');c=JSON.parse(fs.readFileSync(path.join(data,'settings-connection.json')));await until(async()=>!(await list()).busy,'startup');
 await command('music=play');await until(async()=>(await host('media.read')).title==='合成歌曲 A','original music');
 await action('enable','open-hooks');await until(async()=>(await host('media.read')).title==='社区替换：播放器信息','actual host replacement');ok('real music processing replaced by plugin');await action('disable','open-hooks');await until(async()=>(await host('media.read')).title==='合成歌曲 A','restore current source');ok('removing hook recomputes current host source');await command('music-stop');
 await action('enable','open-process');await until(()=>fs.existsSync(path.join(data,'mods/open-process/mod.log'))&&fs.readFileSync(path.join(data,'mods/open-process/mod.log'),'utf8').includes('helper:hello from managed helper'),'helper echo');ok('packaged helper communicates through host-managed pipes');const button=(await list()).resources.find(x=>x.key==='helper-crash');await host('mods.invoke',{handle:button.handle,value:''});await sleep(300);assert((await mod('open-process')).enabled);await command('music-stop');ok('helper exit 73 leaves host and plugin responsive');await action('disable','open-process');await until(async()=>!(await mod('open-process')).loaded,'helper unload');
 await action('enable','open-stream-view');assert((await mod('open-stream')).enabled);await until(()=>media()&&+media()[6]>4,'stream video frames');assert(+media()[7]>0,'PCM samples submitted');ok('required stream provider auto-starts; video frames and PCM enter real host media pipeline');await capture('stream-host');
 await control('pause');await until(()=>media()&&+media()[3]===4,'pause');const paused=+media()[5];await sleep(250);assert(Math.abs(+media()[5]-paused)<.03);ok('community stream pause freezes host timeline');await control('seek');await until(()=>media()&&Math.abs(+media()[5]-1)<.03,'seek');ok('community stream seek while paused');await control('play');await until(()=>media()&&+media()[3]===3&&+media()[5]>1.1,'resume');await control('mute');await control('unmute');ok('stream resume and mute/unmute retain valid playback');await action('disable','open-stream');assert((await mod('open-stream')).enabled);ok('provider disable blocked by actual consumer dependency');await action('disable','open-stream',true);await until(async()=>!(await mod('open-stream')).loaded&&!(await mod('open-stream-view')).loaded,'stream cascade drain');ok('stream session CLOSE and provider DLL drain in dependency order');
 await action('enable','open-browser');await until(()=>fs.existsSync(path.join(data,'mods/open-browser/browser-message.txt')),'WebView ready',30000);assert(fs.readFileSync(path.join(data,'mods/open-browser/browser-message.txt'),'utf8').includes('browser-ready'));
 cdp=await chromium.connectOverCDP('http://127.0.0.1:19322');const page=cdp.contexts().flatMap(x=>x.pages()).find(x=>x.url().includes('about:blank'));assert(page,'actual embedded WebView page');await page.locator('#text').fill('你好，社区 WebView2');await page.getByRole('button',{name:'发送'}).click();await until(()=>fs.readFileSync(path.join(data,'mods/open-browser/browser-message.txt'),'utf8').includes('你好，社区 WebView2'),'browser message');await page.screenshot({path:path.join(out,'webview-real.png')});ok('real WebView2 HTML, Chinese text input, button and callback operate in host view');await command('dpi=1.5');await sleep(700);const size=await page.evaluate(()=>({w:innerWidth,h:innerHeight,dpr:devicePixelRatio}));assert(size.w>0&&size.h>0);ok('view remains live after host layout/DPI test retarget');await cdp.close();cdp=null;await action('disable','open-browser');await until(async()=>!(await mod('open-browser')).loaded,'browser close',30000);assert(fs.existsSync(path.join(data,'mods/open-browser/browser-closed.txt')));ok('browser controller closes before DLL unload');await command('dpi=1');
 await action('enable','open-lifecycle');await action('disable','open-lifecycle');await until(async()=>(await mod('open-lifecycle')).pendingRestart,'delayed thread restart state',6500);assert((await mod('open-lifecycle')).loaded);await command('music-stop');ok('delayed external thread keeps DLL loaded and reports restart required; main UI still responds');await until(async()=>!(await mod('open-lifecycle')).loaded,'thread joins',5000);ok('DLL unloads only after external thread actually exits');
 for(let i=0;i<2;i++){await action('enable','open-browser');await until(()=>fs.existsSync(path.join(data,'mods/open-browser/browser-created.txt')),'browser re-create',30000);await sleep(700);await action('disable','open-browser');await until(async()=>!(await mod('open-browser')).loaded,'browser repeated drain',30000);}ok('repeated browser enable/close drains view lifetime');
 fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({passed:true,data,checks,webViewSize:size},null,2));
 }catch(e){fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({passed:false,data,checks,error:String(e)},null,2));throw e;}
 finally{if(cdp)await cdp.close();if(core?.exitCode===null){fs.writeFileSync(path.join(data,'exit.request'),'exit');await Promise.race([new Promise(r=>core.once('exit',r)),sleep(20000).then(()=>{throw Error('core exit did not drain');})]);}}
})().catch(e=>{console.error(String(e));process.exitCode=1;});

